# Python 程序设计 15 题
SEED = [
  {
    "subject": "Python程序设计", "question_type": "读程序写结果",
    "question": r"写出下面代码的输出：\n```python\nlst = [1, 2, 3, 4, 5]\nprint([x*x for x in lst if x % 2 == 0])\n```",
    "answer": r"`[4, 16]`",
    "key_breakthrough": r"列表推导式的语法是 `[表达式 for 变量 in 可迭代对象 if 条件]`。先过滤（x%2==0 → 2 和 4），再对保留项求平方（4 和 16）。顺序别搞反：先 for 遍历，再 if 过滤，最后对通过的项求表达式。",
    "knowledge_points": ["列表推导式", "过滤", "可迭代对象"],
    "knowledge_review": r"列表推导式是 Python 的特色语法，比等价的 for 循环更简洁且通常更快。完整形式：`[expr for item in iterable if cond]`，支持多个 for（嵌套）和多个 if。等价写法是嵌套 for+append，但推导式更 Pythonic。也可写成集合推导 `{...}` 和字典推导 `{k:v for ...}`。易错点：① 表达式写在最前面而不是最后（与数学集合记法一致，但初学者常写反）；② 推导式中不要做有副作用的操作（可读性差）。",
    "extensions": [r"用列表推导式生成 1~20 中所有能被 3 整除但不能被 5 整除的数。", r"写出上述代码的等价 for 循环版本。"],
  },
  {
    "subject": "Python程序设计", "question_type": "编程题",
    "question": r"编写函数统计一个字符串中每个单词的出现次数，返回字典。\n```python\ndef word_count(s: str) -> dict:\n```",
    "answer": r"```python\ndef word_count(s):\n    d = {}\n    for w in s.lower().split():\n        d[w] = d.get(w, 0) + 1\n    return d\n```\n或用 `collections.Counter(s.lower().split())`。",
    "key_breakthrough": r"`dict.get(key, 0)` 是计数套路的核心：键不存在时返回 0，避免 KeyError，一句完成「取旧值 + 1」。更 Pythonic 的做法是直接用标准库 `collections.Counter`。",
    "knowledge_points": ["字典", "计数", "get方法", "Counter"],
    "knowledge_review": r"字典是键值映射，底层哈希表，查找平均 O(1)。计数三法：① `d[k] = d.get(k,0)+1`；② `d.setdefault(k,0); d[k]+=1`；③ `collections.Counter`（最简洁，还提供 most_common 等方法）。处理文本时通常先 lower() 统一大小写、split() 按空白切分（split() 不带参数会自动处理多个空格）。易错点：直接用 `d[k] += 1` 会因键不存在抛 KeyError。",
    "extensions": [r"返回出现次数最多的前 3 个单词。", r"若需忽略标点符号，应如何预处理？"],
  },
  {
    "subject": "Python程序设计", "question_type": "分析题",
    "question": r"解释 Python 中 `*args` 和 `**kwargs` 的作用，并举例说明。",
    "answer": r"`*args` 接收任意数量的位置参数，打包成元组；`**kwargs` 接收任意数量的关键字参数，打包成字典。常用于装饰器、函数转发。",
    "key_breakthrough": r"`*` 解包位置、收集成元组；`**` 解包/收集字典。同一个符号在「函数定义处」表示收集，在「调用处」表示解包——记住这个对称性就全通了。",
    "knowledge_points": ["可变参数", "args", "kwargs", "解包"],
    "knowledge_review": r"定义函数时 `def f(*args, **kwargs)` 可接收任意参数；调用时 `f(*lst, **d)` 可把序列/字典解包成参数。典型用途：装饰器包装任意函数（`def wrapper(*args, **kwargs): return func(*args, **kwargs)`）、参数转发。命名上 args/kwargs 只是约定，关键是 `*` 和 `**`。参数顺序：位置参数 → 默认参数 → *args → 关键字参数 → **kwargs。易错点：`**kwargs` 的键必须是合法标识符且为字符串。",
    "extensions": [r"写一个计时装饰器，用 *args/**kwargs 包装任意函数。", r"`f(*[1,2], **{'a':3})` 等价于什么调用？"],
  },
  {
    "subject": "Python程序设计", "question_type": "分析题",
    "question": r"说明 Python 中「可变对象与不可变对象」的区别，并解释下面代码为何出现意外结果：\n```python\ndef f(x, lst=[]):\n    lst.append(x)\n    return lst\nprint(f(1), f(2))\n```",
    "answer": r"输出 `[1] [1, 2]`。因为默认参数 `lst=[]` 在函数定义时只创建一次，多次调用共享同一个列表对象（可变默认参数的经典陷阱）。",
    "key_breakthrough": r"**不要用可变对象作为默认参数值**。默认参数在函数定义时求值一次，之后每次调用复用同一对象。正确写法：`def f(x, lst=None): lst = lst or []`（或 `if lst is None: lst = []`）。",
    "knowledge_points": ["可变对象", "不可变对象", "默认参数", "函数定义时求值"],
    "knowledge_review": r"不可变对象：int、float、str、tuple、frozenset（修改会创建新对象）；可变对象：list、dict、set（原地修改）。关键影响：① 函数传参是「对象引用传递」，对可变对象的原地修改会影响调用者；② 默认参数在 def 语句执行时求值一次（不是每次调用）。经典坑：`def f(lst=[])` 会累积状态。正确模式是用 None 作哨兵。易错点：`lst or []` 在 lst 为空列表时也会新建（通常符合预期），但严格区分「空列表」和「None」语义时应用 `if lst is None`。",
    "extensions": [r"写出修正后的函数，使两次调用互不影响。", r"解释 `a = [1,2]; b = a; b.append(3)` 后 a 的值。"],
  },
  {
    "subject": "Python程序设计", "question_type": "编程题",
    "question": r"编写一个生成器函数，依次产生斐波那契数列的前 n 项。",
    "answer": r"```python\ndef fib(n):\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b\n```",
    "key_breakthrough": r"生成器用 `yield` 而非 `return`：函数执行到 yield 时暂停并返回值，下次调用从暂停处继续，**状态自动保留**。注意 `a, b = b, a+b` 是元组解包赋值，右侧先全部求值，避免了用临时变量。",
    "knowledge_points": ["生成器", "yield", "惰性求值", "元组解包"],
    "knowledge_review": r"生成器是惰性求值的迭代器：只在需要时计算下一个值，内存占用 O(1)，可表示无限序列。含 yield 的函数调用后返回生成器对象，用 next() 或 for 遍历。与列表的区别：生成器不存储全部元素（省内存），但只能遍历一次。yield from 可委托给子生成器。易错点：① 生成器只能消费一次，遍历完就耗尽；② `a,b = b,a+b` 的并行赋值是关键，写成两行顺序赋值会出错。",
    "extensions": [r"写一个产生无限斐波那契序列的生成器。", r"生成器表达式与列表推导式在内存上有何差异？"],
  },
  {
    "subject": "Python程序设计", "question_type": "分析题",
    "question": r"简述 Python 的 GIL（全局解释器锁），它带来什么影响？如何绕过？",
    "answer": r"GIL 保证同一时刻只有一个线程执行 Python 字节码，使 CPU 密集型多线程无法真正并行。绕过方式：多进程（multiprocessing）、C 扩展释放 GIL、使用 asyncio 处理 IO 密集型、换用无 GIL 的实现或版本。",
    "key_breakthrough": r"GIL 只影响 **CPU 密集型的多线程**（无法利用多核），**IO 密集型多线程依然有效**（等待 IO 时会释放 GIL）。所以「要不要用多线程」取决于任务类型。",
    "knowledge_points": ["GIL", "多线程", "多进程", "并发"],
    "knowledge_review": r"CPython 用 GIL 保护内存管理的引用计数，导致同一进程内多线程无法并行执行字节码（即使在多核上）。影响：CPU 密集型任务用多线程几乎无加速，甚至因切换而变慢；IO 密集型（网络、文件）在等待时释放 GIL，多线程仍有效。替代方案：① multiprocessing（多进程，各有独立 GIL，可多核，但开销大、通信需序列化）；② concurrent.futures 统一接口；③ asyncio（协程，单线程并发，适合大量 IO）；④ NumPy 等 C 扩展在计算时释放 GIL，能真正并行。易错点：以为多线程一定能加速，实际取决于任务类型。",
    "extensions": [r"比较 threading 与 multiprocessing 在 CPU 密集任务下的耗时差异。", r"asyncio 适合什么场景？与多线程的区别？"],
  },
  {
    "subject": "Python程序设计", "question_type": "编程题",
    "question": r"用面向对象实现一个简单的栈（Stack）类，支持 push、pop、peek、is_empty 和 __len__。",
    "answer": r"```python\nclass Stack:\n    def __init__(self): self._items = []\n    def push(self, x): self._items.append(x)\n    def pop(self): return self._items.pop()\n    def peek(self): return self._items[-1]\n    def is_empty(self): return len(self._items) == 0\n    def __len__(self): return len(self._items)\n```",
    "key_breakthrough": r"用列表尾部（append/pop）作为栈顶，因为 list 尾部的增删是 O(1)（头部 insert(0) 是 O(n)）。实现 `__len__` 后即可用 `len(stack)`，这是 Python 的「鸭子类型 + 魔术方法」风格。",
    "knowledge_points": ["类", "栈", "魔术方法", "封装"],
    "knowledge_review": r"Python 类的基本结构：`__init__` 构造、`self` 指向实例、下划线前缀表示私有约定（`_items`）。魔术方法（dunder）让自定义类支持内置操作：`__len__`（len()）、`__getitem__`（索引）、`__iter__`（可迭代）、`__str__`/`__repr__`（打印）。用 list 实现栈时，栈顶用列表尾部（append/pop 均 O(1) 摊还）。易错点：① 忘记 self 参数；② 用 `items = []` 作类变量会导致所有实例共享（应放在 `__init__` 里）；③ pop 空栈会抛 IndexError。",
    "extensions": [r"加入 pop 空栈时的异常处理。", r"实现 __iter__ 使栈可用 for 遍历。"],
  },
  {
    "subject": "Python程序设计", "question_type": "分析题",
    "question": r"说明 `is` 与 `==` 的区别，并解释为何 `[] is []` 为 False 而小整数 `1 is 1` 可能为 True。",
    "answer": r"`==` 比较值（内容）是否相等，`is` 比较是否为同一个对象（身份，即 id() 是否相同）。小整数（-5~256）和短字符串被 Python 缓存复用（驻留），所以 `1 is 1` 为 True，但新建的列表每次都是不同对象。",
    "key_breakthrough": r"`is` 判断的是「身份证号（id）是否相同」，`==` 判断的是「长相（值）是否相同」。判断 None 时用 `x is None`（惯例），比较数值内容一律用 `==`。",
    "knowledge_points": ["is与==", "对象身份", "整数缓存", "驻留"],
    "knowledge_review": r"`is` 比较对象身份（id(obj) 是否相同），`==` 调用 `__eq__` 比较值。CPython 对小整数（-5~256）和部分短字符串做驻留（interning），使其复用同一对象，因此 `1 is 1`、`'a' is 'a'` 可能为 True——但这是实现细节，**不应依赖**。判断单例 None 用 `is`（PEP 8 惯例，因为 None 是单例）。易错点：用 `is` 比较数值或字符串内容会得到不确定结果（如 `1000 is 1000` 可能为 False），这是经典面试题陷阱。",
    "extensions": [r"验证 `1000 is 1000` 与 `1 is 1` 的结果差异。", r"为什么判断 None 推荐用 is 而不是 ==？"],
  },
  {
    "subject": "Python程序设计", "question_type": "编程题",
    "question": r"编写程序读取一个文本文件，统计其中行数、单词数和字符数（类似 wc 命令）。",
    "answer": r"```python\nwith open(f, encoding='utf-8') as fp:\n    lines = fp.readlines()\nnl, nw, nc = len(lines), sum(len(l.split()) for l in lines), sum(len(l) for l in lines)\n```",
    "key_breakthrough": r"用 `with open(...)` 上下文管理器，文件会自动关闭（即使发生异常），比手动 close 安全。三个统计量分别用 len(lines)、split() 计数和 len(字符串)。",
    "knowledge_points": ["文件操作", "with语句", "上下文管理器", "编码"],
    "knowledge_review": r"`with open(path, mode, encoding=...) as f:` 是读写文件的标准写法，退出 with 块自动关闭文件。常见模式：r（读）、w（写，清空）、a（追加）、rb/wb（二进制）。读法：read()（全部）、readline()（一行）、readlines()（列表）或直接迭代文件对象（最省内存）。中文文本务必指定 encoding='utf-8'（Windows 默认 gbk 易乱码）。易错点：① 忘记指定编码导致中文乱码；② 用 read() 读大文件导致内存爆炸（应逐行迭代）。",
    "extensions": [r"改为逐行读取以支持超大文件。", r"递归统计一个目录下所有 .py 文件的总行数。"],
  },
  {
    "subject": "Python程序设计", "question_type": "分析题",
    "question": r"什么是装饰器？写出一个统计函数运行时间的装饰器。",
    "answer": r"```python\nimport time\ndef timer(func):\n    def wrapper(*args, **kwargs):\n        t0 = time.time()\n        r = func(*args, **kwargs)\n        print(f'{func.__name__} 耗时 {time.time()-t0:.3f}s')\n        return r\n    return wrapper\n```\n用 `@timer` 装饰目标函数。",
    "key_breakthrough": r"装饰器本质是「**接受函数、返回函数**」的高阶函数。用 `@` 语法糖等价于 `f = timer(f)`。内部 wrapper 用 `*args/**kwargs` 接收任意参数并转发，用 `functools.wraps` 保留原函数的元信息。",
    "knowledge_points": ["装饰器", "闭包", "高阶函数", "wraps"],
    "knowledge_review": r"装饰器用于在不修改原函数代码的前提下增加功能（日志、计时、权限、缓存）。原理：闭包 + 高阶函数。`@decorator` 等价于 `func = decorator(func)`。带参数的装饰器需要三层嵌套（外层接收装饰器参数）。关键细节：用 `functools.wraps(func)` 装饰 wrapper，否则原函数的 `__name__`、`__doc__` 会被覆盖（影响调试和文档生成）。多个装饰器按「自下而上」顺序应用。易错点：忘记 return 原函数的返回值（导致调用结果变成 None）。",
    "extensions": [r"写一个带参数的装饰器（如 @retry(times=3)）。", r"为什么推荐用 functools.wraps？不用会有什么问题？"],
  },
  {
    "subject": "Python程序设计", "question_type": "编程题",
    "question": r"用正则表达式从一段文本中提取所有邮箱地址。",
    "answer": r"```python\nimport re\nre.findall(r'[\w.+-]+@[\w-]+\.[\w.]+', text)\n```",
    "key_breakthrough": r"邮箱的通用模式：用户名（字母数字 . _ % + -）+ @ + 域名 + 点 + 后缀。用 `[\w.+-]+` 匹配用户名，`[\w-]+\.[\w.]+` 匹配域名，无需写复杂的完整 RFC 正则。",
    "knowledge_points": ["正则表达式", "re模块", "findall", "字符类"],
    "knowledge_review": r"re 模块核心函数：findall（所有匹配）、search（第一个）、match（从开头）、sub（替换）、split（分割）。常用元字符：`.` 任意字符、`\w` 单词字符、`\d` 数字、`+` 一次以上、`*` 零次以上、`?` 零或一次、`[]` 字符类、`()` 分组。用原始字符串 `r'...'` 避免反斜杠转义麻烦。复杂匹配建议用 `re.compile` 预编译并命名分组。易错点：① 贪婪匹配（用 `?` 转非贪婪）；② 完全校验邮箱的正则极其复杂，实际用简化模式即可。",
    "extensions": [r"提取所有中国大陆手机号（1[3-9]\d{9}）。", r"用 sub 把文本中的手机号中间四位替换成 ****。"],
  },
  {
    "subject": "Python程序设计", "question_type": "分析题",
    "question": r"简述列表（list）与元组（tuple）的区别及各自适用场景。",
    "answer": r"list 可变、用 []、适合需要增删改的数据集合；tuple 不可变、用 ()、适合固定结构（坐标、记录）、可作字典键、性能略好且更安全。",
    "key_breakthrough": r"核心区别就一个字：**可变性**。由此派生出：能否作字典键（tuple 可以，list 不行）、能否原地修改、内存占用（tuple 更紧凑）。「不可变」不是缺点，而是表达「这组数据不该被改」的语义。",
    "knowledge_points": ["list", "tuple", "可变性", "哈希"],
    "knowledge_review": r"list 是动态数组，支持增删改（append/insert/remove/pop），查找 O(n)、按下标访问 O(1)。tuple 是不可变序列，创建后不可修改。影响：① 只有不可变（可哈希）对象才能作 dict 的键或 set 的元素，所以 tuple 可以、list 不行；② tuple 可作为函数返回多个值的载体，也用于解包（`a, b = t`）；③ tuple 因不可变，Python 可做一定优化，创建和访问略快。易错点：tuple 里的元素本身若可变（如 `([1,2], 3)`），该元素仍可修改；单元素 tuple 必须写 `(1,)` 而非 `(1)`。",
    "extensions": [r"为什么 `(1)` 不是元组而 `(1,)` 才是？", r"用 tuple 作字典键举例（如坐标 → 值）。"],
  },
  {
    "subject": "Python程序设计", "question_type": "编程题",
    "question": r"编写函数，对字典按值（value）降序排序并返回前 k 个键值对。",
    "answer": r"```python\nsorted(d.items(), key=lambda kv: kv[1], reverse=True)[:k]\n```",
    "key_breakthrough": r"`sorted` 的 `key` 参数指定排序依据：`key=lambda kv: kv[1]` 表示按每个 (key, value) 元组的第 1 项（即 value）排序。加 `reverse=True` 降序，最后切片取前 k 个。",
    "knowledge_points": ["排序", "sorted", "lambda", "字典"],
    "knowledge_review": r"`sorted(iterable, key=..., reverse=...)` 返回新列表（不修改原对象），`list.sort()` 则原地排序。`key` 是一个函数，作用于每个元素产生排序键。按字典值排序用 `d.items()` + `key=lambda kv: kv[1]`（也可用 `operator.itemgetter(1)`，更快）。Python 3.7+ 字典保持插入顺序，但排序后返回的是列表（如需字典可用 dict() 构造）。易错点：`sorted(d)` 默认按键排序而非值；混淆 `sorted(d.items())` 与 `d.sort()`（字典没有 sort 方法）。",
    "extensions": [r"按值降序、值相同时按键升序，如何写 key？", r"用 collections.Counter 的 most_common(k) 实现同样效果。"],
  },
  {
    "subject": "Python程序设计", "question_type": "分析题",
    "question": r"解释 Python 的异常处理机制（try/except/else/finally），并说明 else 和 finally 各自的作用。",
    "answer": r"try 中放可能出错的代码；except 捕获并处理异常；else 在**未发生异常时**执行；finally **无论是否异常都会执行**（常用于释放资源）。",
    "key_breakthrough": r"`else` 是「没出事才做」，`finally` 是「无论如何都要做」。资源释放放 finally（或用 with），成功后才执行的逻辑放 else（可让 try 块更聚焦，只放真正可能出错的代码）。",
    "knowledge_points": ["异常处理", "try-except", "finally", "else"],
    "knowledge_review": r"异常处理结构：`try` → `except 异常类型 as e` → `else` → `finally`。执行流程：try 无异常则执行 else；有异常则匹配 except；无论如何最后执行 finally（即使 return 或异常未捕获也会执行，常用于关闭文件、释放锁）。可捕获多个异常类型、用 `except Exception` 兜底（但不建议吞掉所有异常）、用 `raise` 重新抛出。常见异常：ValueError、TypeError、KeyError、IndexError、FileNotFoundError、ZeroDivisionError。易错点：① 捕获过于宽泛掩盖 bug；② finally 中的 return 会覆盖前面的 return（应避免）。",
    "extensions": [r"写示例说明 finally 中的 return 会覆盖 try 中的 return。", r"如何自定义异常类？何时该用？"],
  },
  {
    "subject": "Python程序设计", "question_type": "编程题",
    "question": r"使用 NumPy 创建一个 5×5 的随机整数矩阵（0~9），计算每行最大值、每列均值和整个矩阵的和。",
    "answer": r"```python\nimport numpy as np\na = np.random.randint(0, 10, (5, 5))\nrow_max = a.max(axis=1)\ncol_mean = a.mean(axis=0)\ntotal = a.sum()\n```",
    "key_breakthrough": r"NumPy 的核心是 **axis 参数**：`axis=0` 沿「行方向」压缩（对每列操作），`axis=1` 沿「列方向」压缩（对每行操作）。记住「axis 是你要消掉的维度」就不容易搞混。",
    "knowledge_points": ["NumPy", "数组", "axis", "向量化"],
    "knowledge_review": r"NumPy 提供多维数组 ndarray 与向量化运算，避免 Python 循环（快几十倍）。创建：np.array、np.zeros、np.ones、np.arange、np.random.randint。聚合：max/min/mean/sum/std，均支持 axis。shape 属性查看形状，reshape 改变形状。广播机制让不同形状数组可运算。易错点：① axis 方向搞反（axis=0 是「按列」= 跨行聚合，结果长度等于列数）；② 用 `a * b` 是逐元素相乘，矩阵乘法用 `a @ b` 或 np.dot。",
    "extensions": [r"求矩阵中最大元素所在的位置（np.argmax + unravel_index）。", r"对比 NumPy 向量化与纯 Python 循环在百万级数据上的耗时。"],
  },
]
