# C 语言程序设计 20 题
SEED = [
  {
    "subject": "C语言程序设计", "question_type": "读程序写结果",
    "question": r"写出下面程序的运行结果：\n```c\n#include <stdio.h>\nint main() {\n    int a[] = {1,2,3,4,5};\n    int *p = a;\n    printf(\"%d %d\\n\", *(p+2), *p+2);\n    return 0;\n}\n```",
    "answer": r"输出：`3 3`",
    "key_breakthrough": r"分清 `*(p+2)` 与 `*p+2`：`*` 的优先级高于 `+`，所以 `*p+2` 是「先取 `*p` 得 1 再加 2」= 3；而 `*(p+2)` 是「指针先移动 2 个 int 位置再解引用」= a[2] = 3。两者结果恰好都是 3，但含义完全不同——这是出题人故意设计的陷阱。",
    "knowledge_points": ["指针运算", "运算符优先级", "数组与指针"],
    "knowledge_review": r"数组名 a 在多数表达式中退化为指向首元素的指针（int*）。`p+i` 的偏移量是 `i * sizeof(int)` 字节，不是 i 字节。运算符优先级：`*`（解引用）> `+`（加法），所以 `*p+2` 等价于 `(*p)+2`。易错点：`*p++` 与 `(*p)++` 完全不同——前者是指针后移（先取 `*p` 再 p++），后者是值自增。",
    "extensions": [r"把 `*(p+2)` 改成 `p[2]` 结果是否相同？为什么？", r"若 a 是 char 数组，`p+2` 的字节偏移是多少？"],
  },
  {
    "subject": "C语言程序设计", "question_type": "编程题",
    "question": r"编写一个函数，将字符串原地逆置（不使用额外数组）。\n```c\nvoid reverse(char *s);\n```",
    "answer": r"双指针首尾交换：```c\nvoid reverse(char *s) {\n    char *end = s;\n    if (!s) return;\n    while (*end) end++;\n    end--;\n    while (s < end) {\n        char t = *s; *s = *end; *end = t;\n        s++; end--;\n    }\n}\n```",
    "key_breakthrough": r"用两个指针分别从头部和尾部向中间靠拢，每次交换所指字符，直到两指针相遇或交叉（`s < end` 为循环条件）。关键是先让 end 指向最后一个有效字符（跳过 '\0' 后回退一位）。",
    "knowledge_points": ["字符串", "双指针", "原地算法", "指针"],
    "knowledge_review": r"C 字符串以 '\0' 结尾，长度用 strlen 或遍历到 '\0' 获得。原地逆置的标准做法是双指针，时间复杂度 O(n)，空间 O(1)。易错点：① 忘记处理空指针或空串（`end--` 会越界）；② 循环条件写成 `s != end` 在偶数长度时会漏掉中间或死循环，用 `s < end` 最稳妥。",
    "extensions": [r"改用下标（数组）方式实现逆置。", r"如何只逆置字符串中的单词顺序而不逆置单词内部？"],
  },
  {
    "subject": "C语言程序设计", "question_type": "分析题",
    "question": r"说明值传递与地址传递的区别。为什么下面这个 swap 函数无法交换两个整数？\n```c\nvoid swap(int a, int b) { int t = a; a = b; b = t; }\n```",
    "answer": r"因为 C 语言的参数传递是值传递，函数收到的是实参的副本，修改副本不影响原变量。正确写法要传指针并通过解引用修改。",
    "key_breakthrough": r"C 只有值传递一种机制——所谓「地址传递」本质是「传指针的值（地址）」。想在函数内修改调用者的变量，必须把该变量的**地址**传进去，再 `*p = ...` 修改。",
    "knowledge_points": ["值传递", "地址传递", "指针参数", "函数栈帧"],
    "knowledge_review": r"调用函数时，实参的值被复制到形参，形参是独立的局部变量，函数返回时销毁。因此修改形参不会影响实参。若要「带出」结果：① 传指针 `void swap(int *a,int *b){int t=*a;*a=*b;*b=t;}`，调用 `swap(&x,&y)`；② 或用返回值。易错点：很多初学者以为传数组是值传递——数组参数实际退化为指针，所以函数内修改数组元素会影响原数组，这是「看起来像地址传递」的原因。",
    "extensions": [r"写出正确的 swap 及调用方式。", r"若要在函数内修改一个指针变量本身（如 malloc 后赋给外面），参数该怎么写？（提示：二级指针）"],
  },
  {
    "subject": "C语言程序设计", "question_type": "编程题",
    "question": r"用递归实现求 n 的阶乘，并说明递归的两个必要条件及潜在问题。",
    "answer": r"```c\nlong long fact(int n) {\n    if (n <= 1) return 1;\n    return n * fact(n - 1);\n}\n```",
    "key_breakthrough": r"递归两要素：**递归出口（base case，n<=1 返回 1）** + **递归式（n*fact(n-1)，规模递减）**。缺一不可，否则无限递归栈溢出。",
    "knowledge_points": ["递归", "递归出口", "栈溢出", "阶乘"],
    "knowledge_review": r"递归是函数调用自身，系统用调用栈保存每层现场。必须保证：① 有出口（否则栈溢出）；② 每次递归规模向出口收敛。阶乘递归深度 n，空间 O(n)，时间 O(n)。潜在问题：① n 过大栈溢出；② long long 存不下大阶乘（20! 约 2.4e18，21! 溢出）；③ 朴素递归存在重复计算（如斐波那契 O(2^n)），可用记忆化或改迭代。易错点：忘记 `n<=1` 而写 `n==1`，则 fact(0) 会无限递归。",
    "extensions": [r"把阶乘改成迭代实现，比较两者优劣。", r"递归求斐波那契为何低效？如何优化？"],
  },
  {
    "subject": "C语言程序设计", "question_type": "分析题",
    "question": r"解释 `int *p[5]` 与 `int (*p)[5]` 的区别。",
    "answer": r"`int *p[5]` 是指针数组（数组，含 5 个 int* 元素）；`int (*p)[5]` 是数组指针（指针，指向含 5 个 int 的数组）。",
    "key_breakthrough": r"看标识符 p 先和谁结合：`[]` 优先级高于 `*`，所以 `int *p[5]` 中 p 先与 `[5]` 结合 → 数组；`int (*p)[5]` 用括号强制 p 先与 `*` 结合 → 指针。**口诀：括号改变结合顺序。**",
    "knowledge_points": ["指针数组", "数组指针", "运算符优先级", "复杂声明"],
    "knowledge_review": r"复杂声明的阅读方法（右左法则）：从标识符出发，先向右看（[] 或 ()），再向左看（* 或 类型），遇括号则跳出一层。`int *p[5]`：p 是数组[5]，元素是 int*。`int (*p)[5]`：p 是指针，指向 int[5]。应用：指针数组常用于字符串数组 `char *names[]`；数组指针常用于二维数组传参 `void f(int (*p)[5])`。易错点：二维数组名 a 的类型是 `int (*)[5]`（数组指针），不是 `int**`——这是传参时最常见的类型不匹配错误。",
    "extensions": [r"写出用数组指针遍历二维数组 `int a[3][5]` 的代码。", r"`char *p` 与 `char p[]` 作为函数参数是否等价？"],
  },
  {
    "subject": "C语言程序设计", "question_type": "编程题",
    "question": r"编写程序，从键盘读入 10 个整数存入数组，用冒泡排序升序排列后输出。",
    "answer": r"```c\nfor (int i = 0; i < n-1; i++)\n    for (int j = 0; j < n-1-i; j++)\n        if (a[j] > a[j+1]) { int t=a[j]; a[j]=a[j+1]; a[j+1]=t; }\n```",
    "key_breakthrough": r"冒泡排序核心：每趟通过相邻比较交换把「当前未排序部分的最大值」推到末尾，因此第 i 趟后末尾 i 个已就位，内层只需循环 `n-1-i` 次。加一个 `swapped` 标志可提前结束（已有序时降到 O(n)）。",
    "knowledge_points": ["冒泡排序", "数组", "双重循环", "稳定排序"],
    "knowledge_review": r"冒泡排序：重复扫描，相邻逆序则交换。时间复杂度：最好 O(n)（已有序 + 提前退出标志）、平均与最坏 O(n²)。空间 O(1)，**稳定**（相等不交换）。内层上界 `n-1-i` 是关键优化，避免已就位部分的重复比较。易错点：内层写成 `j < n-1` 不会错但会多比较已就位元素；忘记 `swapped` 标志则已有序时仍 O(n²)。",
    "extensions": [r"加入 swapped 标志改写，并说明最好情况复杂度。", r"冒泡排序在什么输入下交换次数最多？（逆序，n(n-1)/2 次）"],
  },
  {
    "subject": "C语言程序设计", "question_type": "分析题",
    "question": r"说明 malloc / calloc / realloc 的区别及使用注意事项。",
    "answer": r"malloc 分配指定字节且不初始化；calloc 分配 n 个 size 字节并清零；realloc 调整已分配内存大小（可能移动）。三者失败均返回 NULL，使用后必须 free，且不可重复释放。",
    "key_breakthrough": r"三条铁律：**① 判空（可能失败返回 NULL）；② 配对 free（防内存泄漏）；③ 释放后置 NULL（防野指针/重复释放）**。",
    "knowledge_points": ["动态内存分配", "malloc", "calloc", "realloc", "内存泄漏"],
    "knowledge_review": r"堆内存由程序员手动管理。malloc(size) 分配 size 字节，内容未定义（垃圾值）；calloc(n,size) 分配并清零，适合数组；realloc(p,newsize) 调整大小，可能就地扩展或新分配并拷贝（原指针失效，须用返回值）。使用要点：① 检查返回值是否为 NULL；② sizeof 计算类型大小（`p = malloc(n * sizeof(int))`）；③ free 后指针置 NULL；④ 不要 free 非堆内存或重复 free；⑤ realloc 失败时原内存仍有效，应先用临时指针接收。易错点：函数内 malloc 后忘记让调用者 free，造成泄漏。",
    "extensions": [r"写出 realloc 的安全用法（用临时指针接收返回值）。", r"什么是野指针？如何避免？"],
  },
  {
    "subject": "C语言程序设计", "question_type": "读程序写结果",
    "question": r"写出下面程序的输出：\n```c\n#include <stdio.h>\nint f(int x) { static int s = 0; s += x; return s; }\nint main() {\n    printf(\"%d %d\\n\", f(1), f(2));\n    return 0;\n}\n```",
    "answer": r"输出顺序未定义（取决于参数求值顺序），常见为 `1 3` 或 `3 3`；但 static 变量 s 会累加，两次调用后 s = 3。",
    "key_breakthrough": r"两个关键点：① **static 局部变量只初始化一次，函数返回后值保留**，所以第二次调用是在第一次结果上累加；② **C 标准未规定函数参数的求值顺序**（gcc 通常从右到左），因此 `printf` 的两个参数谁先算不确定——这是一道考察「未定义行为」意识的经典题。",
    "knowledge_points": ["static局部变量", "参数求值顺序", "未定义行为", "生命周期"],
    "knowledge_review": r"static 局部变量存储在静态存储区（非栈），只初始化一次，生命周期贯穿整个程序，但作用域仍限于函数内。因此它可用于「记住上次调用的状态」。函数参数求值顺序在 C 中是未指定/未定义的，不可依赖（如 `f(i++, i++)` 是典型错误写法）。易错点：① 以为 static 变量每次调用都重新初始化；② 写出依赖参数求值顺序的代码，在不同编译器下结果不同。",
    "extensions": [r"若把 static 去掉，两次调用的结果是什么？", r"如何改写以避免依赖参数求值顺序？"],
  },
  {
    "subject": "C语言程序设计", "question_type": "编程题",
    "question": r"定义结构体 Student（姓名、学号、成绩），编写函数输入 5 个学生信息并按成绩降序输出。",
    "answer": r"```c\ntypedef struct { char name[20]; int id; float score; } Student;\n// 排序用 qsort 或简单选择排序，比较 score\n```",
    "key_breakthrough": r"结构体数组排序时，交换的是**整个结构体变量**（C 允许结构体整体赋值），而不必逐成员交换。用标准库 qsort 时需提供比较函数，注意降序是 `b.score - a.score`（浮点要小心，用比较返回 -1/0/1 更稳）。",
    "knowledge_points": ["结构体", "结构体数组", "排序", "typedef"],
    "knowledge_review": r"结构体把不同类型的数据组合成一个整体。定义：`struct Stu {...};`，配合 typedef 可省写 struct。访问成员用 `.`（变量）或 `->`（指针）。结构体变量可整体赋值（`s1 = s2`），但不能用 `==` 比较（需逐成员）。结构体数组排序：可用选择/冒泡，或 qsort + 比较函数。易错点：① 字符数组成员不能直接 `=` 赋值，要用 strcpy；② qsort 比较函数返回 int，浮点直接相减可能有精度问题。",
    "extensions": [r"用 qsort 实现，并写出比较函数。", r"结构体中 char name[20] 与 char *name 有何区别？"],
  },
  {
    "subject": "C语言程序设计", "question_type": "分析题",
    "question": r"简述 `#include <stdio.h>` 与 `#include \"stdio.h\"` 的区别，以及 `#define` 与 `const` 的区别。",
    "answer": r"`<>` 从系统标准头文件目录搜索，`\"\"` 先从当前源文件目录搜索、找不到再搜系统目录。`#define` 是预处理期的文本替换、无类型、不占内存；`const` 是编译期的只读变量、有类型、占内存、可做类型检查。",
    "key_breakthrough": r"记住时间维度：`#define` 发生在**编译前**（预处理，纯文本替换，编译器看不到它），`const` 发生在**编译时**（有类型的变量，受作用域和类型系统约束）。",
    "knowledge_points": ["预处理", "include", "define", "const", "宏"],
    "knowledge_review": r"预处理指令在编译前处理：#include 插入头文件内容，#define 定义宏（文本替换），#ifdef/#ifndef 条件编译。宏的优点是可用于常量、条件编译、代码生成；缺点是无类型检查、易因优先级出错（宏体应整体加括号）、不便于调试。const 变量有类型和作用域，更安全。易错点：带参数的宏 `#define SQUARE(x) x*x` 在 `SQUARE(a+1)` 时会展开成 `a+1*a+1`，正确写法是 `((x)*(x))`。",
    "extensions": [r"写出一个安全的求最大值宏 MAX(a,b)，并说明为何要加括号。", r"#define 定义的宏如何在调试时看到？（提示：宏在预处理后已不存在）"],
  },
  {
    "subject": "C语言程序设计", "question_type": "编程题",
    "question": r"编写程序统计一个字符串中每个英文字母出现的次数（不区分大小写）。",
    "answer": r"用长度 26 的计数数组，遍历字符串：`cnt[tolower(c)-'a']++`。",
    "key_breakthrough": r"把「字母」映射到数组下标 0~25（`tolower(c) - 'a'`），一句计数搞定——这是**用空间换时间 + 建立字符到下标映射**的经典套路，比 26 次 if 判断优雅得多。",
    "knowledge_points": ["字符串处理", "计数数组", "字符映射", "ctype.h"],
    "knowledge_review": r"字符在 C 中以 ASCII 码存储，'a'~'z' 连续，因此 `c - 'a'` 可直接得到 0~25 的下标。ctype.h 提供 isalpha/tolower/toupper 等便捷函数（注意参数应为 unsigned char 或 EOF，否则负值可能未定义）。计数类问题的通法：确定值域 → 开数组 → 遍历累加 → 输出。易错点：① 忘记判 isalpha 导致把标点也计入；② 大小写未统一导致重复计数。",
    "extensions": [r"改为统计所有字符（含数字、空格）的出现频次。", r"若字符串含中文（多字节），上述方法为何失效？"],
  },
  {
    "subject": "C语言程序设计", "question_type": "分析题",
    "question": r"什么是文件操作的 `r`、`w`、`a`、`rb`、`wb` 模式？fopen 失败时应如何处理？",
    "answer": r"r 只读（文件须存在）、w 只写（存在则清空/不存在则创建）、a 追加写（末尾写入）、b 表示二进制。fopen 失败返回 NULL，必须判空并用 perror 报错后退出，不可继续操作。",
    "key_breakthrough": r"`w` 会**清空**原文件——这是最容易造成数据丢失的坑。若想保留原内容，用 `a`（追加）或 `r+`（读写）。二进制/文本区别在 Windows 下影响换行符转换（\n ↔ \r\n）。",
    "knowledge_points": ["文件操作", "fopen", "文件模式", "错误处理"],
    "knowledge_review": r"文件操作三步：fopen 打开 → 读/写（fscanf/fprintf/fread/fwrite/fgets）→ fclose 关闭。模式串：r（读）、w（写，清空）、a（追加）、+（读写）、b（二进制）。必须检查 fopen 返回值，失败时 perror/strerror 输出原因。用完必须 fclose，否则可能丢失缓冲区数据（写操作在缓冲区未满时未真正落盘）。易错点：① 忘记 fclose；② 用 w 模式打开想读的文件导致内容被清空；③ 二进制和文本模式混用导致换行符问题。",
    "extensions": [r"写程序把一个文本文件复制成另一个文件。", r"如何读取一个未知长度文件的全部内容？"],
  },
  {
    "subject": "C语言程序设计", "question_type": "分析题",
    "question": r"简述位运算符 &、|、^、~、<<、>> 的作用，并写出「判断一个整数第 k 位是否为 1」和「把第 k 位清 0」的表达式。",
    "answer": r"判断第 k 位：`(n >> k) & 1` 或 `n & (1 << k)`；第 k 位清 0：`n &= ~(1 << k)`；第 k 位置 1：`n |= (1 << k)`。",
    "key_breakthrough": r"位运算三板斧：**置 1 用 |，清 0 用 &~，翻转用 ^**。先构造掩码 `1 << k`，再用对应运算符操作即可。",
    "knowledge_points": ["位运算", "掩码", "移位", "嵌入式应用"],
    "knowledge_review": r"位运算直接操作二进制位，效率极高，常用于底层/嵌入式/权限标志/压缩。& 与（都为1则1）、| 或（有1则1）、^ 异或（不同则1）、~ 取反、<< 左移（乘 2^k）、>> 右移（除 2^k，有符号数右移为算术右移，补符号位）。常用技巧：`n & (n-1)` 清除最低位的 1；`n & -n` 取最低位的 1；`a ^ a = 0`（可不用临时变量交换）。易错点：① 移位位数 >= 类型位数是未定义行为；② 对有符号负数右移是实现相关的（通常算术右移）；③ 位运算优先级低于 ==，比较时要加括号。",
    "extensions": [r"如何用一条语句统计一个整数二进制中 1 的个数（n &= n-1 循环）？", r"不用临时变量交换两个整数（异或法），说明原理与风险。"],
  },
  {
    "subject": "C语言程序设计", "question_type": "编程题",
    "question": r"实现单链表的创建（尾插法）、遍历与按值删除结点。",
    "answer": r"尾插法维护 tail 指针；删除需保存前驱 prev，注意删除头结点的特殊情况（或引入哨兵头结点简化）。",
    "key_breakthrough": r"链表操作的难点全在**指针的修改顺序和删除头结点**。用「哨兵头结点（dummy head）」可以统一处理删除头结点的情况，代码更简洁不易错。",
    "knowledge_points": ["单链表", "尾插法", "删除结点", "指针操作"],
    "knowledge_review": r"单链表结点含数据域与 next 指针。尾插法：维护 tail，新结点 `tail->next = node; tail = node;`。删除按值：遍历时保存 prev，`prev->next = cur->next; free(cur);`。若可能删除头结点，要么单独 if 处理，要么用 dummy 头结点（dummy.next 指向真正头结点，统一处理）。时间复杂度：插入 O(1)（已知位置）或 O(n)（尾插无 tail），查找/删除 O(n)。易错点：① 删除后未 free（内存泄漏）；② 修改指针顺序错误导致断链；③ 忘记处理空链表。",
    "extensions": [r"用哨兵头结点改写删除函数。", r"如何判断单链表是否有环（快慢指针）？"],
  },
  {
    "subject": "C语言程序设计", "question_type": "分析题",
    "question": r"说明全局变量、局部变量、static 变量在作用域、生命周期和存储位置上的区别。",
    "answer": r"全局：文件作用域（可 extern 跨文件）、程序全程、静态存储区。局部：块作用域、进入块时创建离开时销毁、栈。static 局部：块作用域、程序全程、静态存储区。static 全局：限制在本文件内（改变链接属性）。",
    "key_breakthrough": r"把「作用域（哪里能访问）」和「生命周期（活多久）」拆开看：static 局部变量是「作用域小但活得久」的典型——这正是它在函数内累加状态的原因。",
    "knowledge_points": ["作用域", "生命周期", "存储类别", "static", "栈与静态区"],
    "knowledge_review": r"存储类别：auto（默认局部，栈）、static（静态区，只初始化一次）、extern（声明外部定义）、register（建议放寄存器，现代编译器多忽略）。全局变量定义在函数外，具有外部链接，其他文件用 extern 声明后可引用；加 static 后变为内部链接，仅本文件可见（良好的封装习惯）。局部变量默认 auto，在栈上，未初始化时为垃圾值；static 局部在静态区，自动初始化为 0。易错点：① 未初始化的局部变量值不确定（不是 0）；② 过多全局变量降低模块独立性，应尽量避免。",
    "extensions": [r"多个源文件共享一个全局变量，应如何定义与声明？", r"为什么建议给仅本文件使用的全局变量加 static？"],
  },
  {
    "subject": "C语言程序设计", "question_type": "分析题",
    "question": r"什么是缓冲区溢出？举例说明 gets 函数的危险及安全替代方案。",
    "answer": r"gets 不检查输入长度，会把超出数组容量的数据写入相邻内存，导致栈破坏甚至被利用执行任意代码。安全替代：fgets(buf, size, stdin)（会保留换行符）或指定宽度的 scanf（如 %19s）。",
    "key_breakthrough": r"危险的本质是「**写入时不检查目标容量**」。任何 `char buf[N]` + 无长度限制的读（gets、scanf %s、strcpy、sprintf）都是潜在溢出点，对应安全版本分别是 fgets、%Ns、strncpy、snprintf。",
    "knowledge_points": ["缓冲区溢出", "gets", "fgets", "安全函数"],
    "knowledge_review": r"缓冲区溢出是 C 程序最常见的安全漏洞：向固定大小的缓冲区写入超长数据，覆盖相邻内存（可能改写返回地址）。经典危险函数：gets（已被 C11 移除）、strcpy、strcat、sprintf、scanf(“%s”)。安全替代：fgets（指定最大读取数）、strncpy/strncat（注意不会自动补 '\0'）、snprintf、scanf(“%19s”)。现代编译器有栈保护（canary）和 ASLR 缓解，但根本解决是写代码时检查边界。易错点：strncpy 在源串超长时不会补 '\0'，需手动 `buf[N-1]='\0'`。",
    "extensions": [r"用 fgets 读取一行并去掉末尾换行符。", r"解释 strncpy 的一个常见陷阱。"],
  },
  {
    "subject": "C语言程序设计", "question_type": "编程题",
    "question": r"编写函数判断一个字符串是否为回文（正读反读相同，忽略大小写与非字母数字字符）。",
    "answer": r"双指针从两端向中间，跳过非字母数字，比较 tolower 后的字符。",
    "key_breakthrough": r"双指针 + 跳过无效字符：先 `while (l < r && !isalnum(s[l])) l++;` 再比较，全部相等则是回文。只需扫半串，O(n) 时间 O(1) 空间。",
    "knowledge_points": ["双指针", "回文", "字符处理", "isalnum"],
    "knowledge_review": r"回文判断的标准解法是双指针（对撞指针）：left 从 0、right 从 len-1 向中间移动，跳过无效字符后比较 tolower 值，一旦不等立即返回 false。时间复杂度 O(n)，空间 O(1)。若要求忽略空格标点，用 isalnum 过滤。易错点：① 未统一大小写；② 忘记跳过非字母数字；③ 边界处理（空串、单字符应返回 true）。",
    "extensions": [r"若允许删除最多一个字符，如何判断能否构成回文？", r"用递归方式实现回文判断。"],
  },
  {
    "subject": "C语言程序设计", "question_type": "分析题",
    "question": r"简述 typedef 的作用及其与 #define 的区别。写出用 typedef 定义函数指针的例子。",
    "answer": r"typedef 给类型起别名（编译期，有类型检查）；#define 是文本替换（预处理期）。函数指针：`typedef int (*Cmp)(int, int);`",
    "key_breakthrough": r"typedef 是「类型别名」而非新类型，它受作用域和类型系统约束；#define 是无脑文本替换。定义复杂类型（尤其函数指针、结构体）时 typedef 能大幅提升可读性。",
    "knowledge_points": ["typedef", "函数指针", "类型别名", "define对比"],
    "knowledge_review": r"typedef 语法：`typedef 原类型 新名字;`，如 `typedef unsigned long ulong;`。常用于：简化复杂声明、提高可移植性（size_t）、定义函数指针类型。与 #define 的区别：typedef 有类型检查、受作用域限制、不能用于条件编译；#define 是预处理替换、无类型、可条件编译。函数指针定义要抓住「返回类型 (*名字)(参数表)」。易错点：`typedef int* P, Q;` 中只有 P 是指针、Q 是 int（* 只修饰第一个）。",
    "extensions": [r"用 typedef 定义的函数指针类型写一个通用排序（类似 qsort）。", r"解释 `typedef int* P, Q;` 的陷阱。"],
  },
  {
    "subject": "C语言程序设计", "question_type": "编程题",
    "question": r"编写程序，从文件 data.txt 读入若干整数，计算平均值并写入 result.txt。",
    "answer": r"fopen 读 → fscanf 循环累加计数 → 求均值 → fopen(\"result.txt\",\"w\") 写入。注意判空与 fclose。",
    "key_breakthrough": r"文件 IO 的通用骨架：`fp = fopen(...); if (!fp) { perror(...); return; }` → 循环读写 → `fclose(fp);`。判空和关闭这两步是得分点，也是实际项目中最容易遗漏的地方。",
    "knowledge_points": ["文件读写", "fscanf", "fprintf", "错误处理"],
    "knowledge_review": r"文本文件读写：fopen 打开，fscanf/fgets 读，fprintf/fputs 写，fclose 关闭。读取到文件尾：fscanf 返回 EOF（-1），或 fgets 返回 NULL（配合 feof 判断）。写文件时注意模式 w 会清空原内容。错误处理：fopen 失败返回 NULL，用 perror 输出具体原因。易错点：① 未判断文件是否成功打开；② 除零（文件为空时 count=0）；③ 忘记 fclose 导致数据未落盘。",
    "extensions": [r"若文件可能很大，如何节省内存（流式读取而非全读入）？", r"如何同时读写一个文件（r+ 模式）？"],
  },
]
