# 批次D：数学物理方程 10 题
SEED = [
  {
    "subject": "数学物理方程", "question_type": "分析题",
    "question": r"对二阶线性偏微分方程 $a_{11}u_{xx}+2a_{12}u_{xy}+a_{22}u_{yy}+\cdots=f$ 进行分类，并说明判别式的判据。",
    "answer": r"令 $\Delta=a_{12}^2-a_{11}a_{22}$：$\Delta>0$ 为双曲型（如波动方程 $u_{tt}=a^2u_{xx}$）；$\Delta=0$ 为抛物型（如热传导方程 $u_t=a^2u_{xx}$）；$\Delta<0$ 为椭圆型（如拉普拉斯方程 $u_{xx}+u_{yy}=0$）。",
    "key_breakthrough": r"判别式与二次曲线的判别（$B^2-4AC$）完全同构：**Δ>0 双曲（两族特征线）→Δ=0 抛物（一族）→Δ<0 椭圆（无实特征线）**。三类方程分别对应振动/传播、扩散/耗散、稳态/平衡三类物理过程，定解条件的提法也因此不同。",
    "knowledge_points": ["偏微分方程分类", "双曲型", "抛物型", "椭圆型"],
    "knowledge_review": r"二阶线性 PDE 的分类由主部（二阶导数项）系数决定。判别式 $\Delta=a_{12}^2-a_{11}a_{22}$（与二次曲线 $Ax^2+Bxy+Cy^2$ 的 $B^2-4AC$ 类比，差一个常数倍）。三类：① 双曲型（$\Delta>0$）：有两条实特征线，描述振动与波的传播，典型是波动方程；定解问题通常是初值问题（给定初始位移和速度）或混合问题；② 抛物型（$\Delta=0$）：一条实特征线，描述扩散、热传导等不可逆过程；提初值+边界条件，解有「无限传播速度」和光滑效应；③ 椭圆型（$\Delta<0$）：无实特征线，描述稳态/平衡（如静电场、稳态温度分布）；提边值问题（Dirichlet、Neumann、Robin），解具有最大值原理和光滑性。变系数方程的分类逐点进行，可能是混合型（如 Tricomi 方程）。易错点：判别式的符号约定（有的教材用 $a_{11}a_{22}-a_{12}^2$，符号相反）；分类只取决于最高阶导数项的系数。",
    "extensions": [r"判断 $u_{xx}+4u_{xy}+u_{yy}=0$ 的类型（Δ=4-1=3>0，双曲）。", r"三类方程各对应什么物理过程？定解条件提法有何不同？"],
  },
  {
    "subject": "数学物理方程", "question_type": "计算题",
    "question": r"用分离变量法求解两端固定弦的自由振动问题：\n$$\begin{cases}u_{tt}=a^2u_{xx},\quad 0<x<L\\ u(0,t)=u(L,t)=0\\ u(x,0)=\varphi(x),\ u_t(x,0)=\psi(x)\end{cases}$$\n写出本征值与本征函数。",
    "answer": r"分离变量 $u=X(x)T(t)$ 得本征值问题 $X''+\lambda X=0,\ X(0)=X(L)=0$。本征值 $\lambda_n=\left(\frac{n\pi}{L}\right)^2$，本征函数 $X_n(x)=\sin\frac{n\pi x}{L}$（$n=1,2,\dots$）。通解 $u=\sum_{n=1}^{\infty}\left(A_n\cos\frac{n\pi a t}{L}+B_n\sin\frac{n\pi a t}{L}\right)\sin\frac{n\pi x}{L}$。",
    "key_breakthrough": r"分离变量法的主线：**① 设 $u=XT$ 代入方程分离出两个常微分方程；② 由齐次边界条件得到本征值问题（Sturm-Liouville）；③ 求本征值和本征函数（本题是 $\sin\frac{n\pi x}{L}$，由边界条件 $X(0)=X(L)=0$ 决定）；④ 用初始条件把解展开成本征函数级数（傅里叶正弦级数），系数由傅里叶公式确定**。",
    "knowledge_points": ["分离变量法", "本征值问题", "傅里叶级数", "弦振动"],
    "knowledge_review": r"分离变量法是求解线性 PDE 定解问题的核心方法，适用于有界区域。步骤：① 设 $u(x,t)=X(x)T(t)$ 代入齐次方程和齐次边界条件；② 得到 $\frac{T''}{a^2T}=\frac{X''}{X}=-\lambda$（因两边分别是 t 和 x 的函数，只能等于常数）；③ 空间部分构成 Sturm-Liouville 本征值问题 $X''+\lambda X=0$ + 齐次边界条件，解得本征值 $\lambda_n$ 与本征函数 $X_n$（构成完备正交系）；④ 时间部分对每个 $\lambda_n$ 解出 $T_n$；⑤ 叠加得通解；⑥ 由初始条件（或非齐次项）用正交性求系数（傅里叶展开）。本题（第一类齐次边界）：$X_n=\sin\frac{n\pi x}{L}$、$\lambda_n=(n\pi/L)^2$，系数 $A_n=\frac2L\int_0^L\varphi(x)\sin\frac{n\pi x}{L}dx$、$B_n=\frac{2}{n\pi a}\int_0^L\psi(x)\sin\frac{n\pi x}{L}dx$。物理意义：$n$ 次谐波频率 $\omega_n=\frac{n\pi a}{L}$，基频 $n=1$。易错点：边界条件必须是齐次的才能直接分离变量（非齐次边界需先做变换齐次化）；本征函数族的正交性。",
    "extensions": [r"若 $\varphi(x)=h\sin(\pi x/L)$，求具体解（只有 n=1 项）。", r"若边界改为自由端（$u_x(0,t)=u_x(L,t)=0$），本征函数变为什么？"],
  },
  {
    "subject": "数学物理方程", "question_type": "计算题",
    "question": r"用达朗贝尔公式求解一维无限长弦的自由振动：$u_{tt}=a^2u_{xx}$，$u(x,0)=\varphi(x)$，$u_t(x,0)=\psi(x)$。",
    "answer": r"$u(x,t)=\frac{1}{2}\left[\varphi(x+at)+\varphi(x-at)\right]+\frac{1}{2a}\int_{x-at}^{x+at}\psi(\xi)\,d\xi$",
    "key_breakthrough": r"达朗贝尔公式的结构很直观：**解 = 初始位移向左右两半传播（各占 1/2）+ 初始速度在区间 $[x-at,\,x+at]$ 上的积分**。做变量代换 $\xi=x+at$、$\eta=x-at$ 可把波动方程化为 $u_{\xi\eta}=0$，直接积分即得。",
    "knowledge_points": ["达朗贝尔公式", "行波法", "波动方程", "特征线"],
    "knowledge_review": r"一维波动方程的通解（行波解）：$u(x,t)=f(x+at)+g(x-at)$，表示两列以速度 a 向相反方向传播的行波的叠加。由初始条件确定 f、g 即得达朗贝尔公式。重要概念：① 依赖区间 $[x-at, x+at]$：解在 (x,t) 处的值只依赖于初始线上该区间内的数据；② 决定区域：受某区间初始扰动影响的时空区域；③ 特征线 $x\pm at=$ 常数，是扰动的传播路径；④ 惠更斯原理（三维）与波的弥散（二维）的差异。半无限长弦问题可用延拓法（奇延拓对应固定端、偶延拓对应自由端）转化为无限长问题求解。易错点：波动方程是双曲型，解无光滑效应（初始函数的奇性会沿特征线传播）；区分「依赖区间」与「决定区域」的方向。",
    "extensions": [r"若 $\varphi(x)=0,\ \psi(x)=\sin x$，求解的具体形式。", r"用奇延拓法求解半无限长弦固定端问题。"],
  },
  {
    "subject": "数学物理方程", "question_type": "计算题",
    "question": r"用分离变量法求解一维热传导方程混合问题：\n$$\begin{cases}u_t=a^2u_{xx},\quad 0<x<L\\ u(0,t)=u(L,t)=0\\ u(x,0)=\varphi(x)\end{cases}$$",
    "answer": r"$u(x,t)=\sum_{n=1}^{\infty}b_n e^{-a^2(n\pi/L)^2 t}\sin\frac{n\pi x}{L}$，其中 $b_n=\frac{2}{L}\int_0^L\varphi(x)\sin\frac{n\pi x}{L}dx$",
    "key_breakthrough": r"热传导方程与波动方程的分离变量步骤几乎一样，差别在时间部分：波动方程是 $T''+\lambda a^2T=0$（振荡，$\cos$/$\sin$），热传导是 $T'+a^2\lambda T=0$（**指数衰减** $e^{-a^2\lambda t}$）。这个衰减因子正是「热量扩散、趋于均匀」的数学体现——高阶谐波（n 大）衰减极快，最终只剩基频。",
    "knowledge_points": ["热传导方程", "分离变量法", "指数衰减", "傅里叶级数"],
    "knowledge_review": r"热传导方程 $u_t=a^2\Delta u$（抛物型），描述温度分布随时间的扩散。分离变量 $u=X(x)T(t)$：$X''+\lambda X=0$（同波动方程，由边界条件定本征值）+ $T'+a^2\lambda T=0$ → $T=e^{-a^2\lambda t}$。因此解是 Fourier 级数乘以随时间指数衰减的因子，高阶项衰减更快（$e^{-n^2}$），这解释了热传导的「光滑化效应」（初始的不连续立即被抹平）。与非齐次方程（有热源）和不同边界条件（第二类 $u_x=0$ 绝热 → 本征函数为 $\cos$；第三类 Newton 冷却）的处理类似，用相应本征函数展开。重要性质：极值原理（温度极值在边界或初始时刻取得）、能量递减、无限传播速度（数学上扰动瞬间传遍全域，但影响极小）。易错点：初始条件只有一个（抛物型只需 $u(x,0)$，不需要 $u_t$）；衰减因子是 $e^{-a^2\lambda_n t}$ 而非 $e^{-a\lambda_n t}$。",
    "extensions": [r"若边界为绝热（$u_x(0,t)=u_x(L,t)=0$），本征函数与解的形式如何变化？", r"求 $t\to\infty$ 时温度的极限（趋于平均值，体现能量守恒）。"],
  },
  {
    "subject": "数学物理方程", "question_type": "分析题",
    "question": r"说明三类边界条件（Dirichlet、Neumann、Robin）的数学形式与物理意义。",
    "answer": r"① 第一类（Dirichlet）：$u|_{\partial\Omega}=f$，给定边界上的函数值（如固定端弦的位移、恒温边界）；② 第二类（Neumann）：$\frac{\partial u}{\partial n}|_{\partial\Omega}=f$，给定法向导数（如绝热边界的热流、自由端弦的受力）；③ 第三类（Robin）：$\left(u+h\frac{\partial u}{\partial n}\right)|_{\partial\Omega}=f$，函数值与法向导数的线性组合（如 Newton 冷却定律、弹性支承端）。",
    "key_breakthrough": r"三类的记忆线索：**Dirichlet 给「值本身」、Neumann 给「变化率（导数）」、Robin 给「两者的组合」**。物理上分别对应「固定/恒温」「自由/绝热」「弹性支承/对流换热」。对椭圆型方程，三类边界条件都可提；对双曲/抛物型，还须配合初始条件。",
    "knowledge_points": ["边界条件", "Dirichlet", "Neumann", "Robin"],
    "knowledge_review": r"定解条件包括初始条件（对含时间变量的发展方程）和边界条件（对有界区域）。三类边界条件：① Dirichlet（第一类）：直接给定边界上的物理量，如固定端弦 $u(0,t)=0$、恒温边界 $u=T_0$；② Neumann（第二类）：给定法向导数，物理上常对应「通量」，如绝热边界 $\frac{\partial u}{\partial n}=0$（热流为零）、自由端弦 $u_x(L,t)=0$（端点不受横向力）；③ Robin（第三类）：线性组合，最典型是 Newton 冷却定律 $-k\frac{\partial u}{\partial n}=h(u-u_{外})$（热流正比于温差）。此外还有：自然边界条件（有界性要求）、周期性边界条件、衔接条件（不同介质交界面上 u 与通量连续）。适定性：解的存在性、唯一性、稳定性（Hadamard 意义下适定）。注意：纯 Neumann 问题（椭圆型）解可能相差一个常数（不唯一），需附加条件（如给定平均值）。易错点：符号（法向导数的正方向是外法向）；Neumann 问题需满足相容条件（对 Poisson 方程，$\int_\Omega f=\oint_{\partial\Omega}g$）。",
    "extensions": [r"写出 Newton 冷却定律对应的 Robin 边界条件表达式。", r"为何 Poisson 方程的纯 Neumann 问题要求相容条件？"],
  },
  {
    "subject": "数学物理方程", "question_type": "计算题",
    "question": r"求圆域内 Laplace 方程的 Dirichlet 问题：\n$$\begin{cases}u_{rr}+\frac1r u_r+\frac{1}{r^2}u_{\theta\theta}=0,\quad r<a\\ u|_{r=a}=f(\theta)\end{cases}$$\n写出分离变量得到的一般解形式。",
    "answer": r"由周期性 $u(\theta)=u(\theta+2\pi)$ 得本征值 $\lambda_n=n^2$，一般解 $u(r,\theta)=\frac{A_0}{2}+\sum_{n=1}^{\infty}\left(\frac{r}{a}\right)^n(A_n\cos n\theta+B_n\sin n\theta)$。由边界条件 $f(\theta)$ 的傅里叶级数定系数：$A_n=\frac{1}{\pi}\int_0^{2\pi}f(\theta)\cos n\theta\,d\theta$，$B_n=\frac{1}{\pi}\int_0^{2\pi}f(\theta)\sin n\theta\,d\theta$。",
    "key_breakthrough": r"极坐标下分离变量 $u=R(r)\Theta(\theta)$：角度部分因**周期性**得本征值 $n^2$（整数，$\cos n\theta$/$\sin n\theta$）；径向部分是 Euler 方程 $r^2R''+rR'-n^2R=0$，解为 $r^n$ 和 $r^{-n}$，由**圆心处有界**舍去 $r^{-n}$。所以解是「$r^n$ 乘以傅里叶级数」——这是圆域问题的典型结构。",
    "knowledge_points": ["拉普拉斯方程", "极坐标", "分离变量", "傅里叶级数"],
    "knowledge_review": r"Laplace 方程 $\Delta u=0$（椭圆型）描述稳态（静电势、稳态温度、不可压缩无旋流）。在圆域用极坐标分离变量：$u=R(r)\Theta(\theta)$ → $\Theta''+\lambda\Theta=0$（周期性条件 $\Theta(\theta)=\Theta(\theta+2\pi)$ 给出 $\lambda=n^2$，$n=0,1,2,\dots$，本征函数 $1,\cos n\theta,\sin n\theta$）+ 径向 Euler 方程 $r^2R''+rR'-n^2R=0$（解 $R=r^{\pm n}$，圆内有界舍去 $r^{-n}$；$n=0$ 时为常数和 $\ln r$，舍去 $\ln r$）。一般解即 Poisson 积分公式的级数形式。重要性质：调和函数的平均值定理（圆心值 = 圆周平均值）、极值原理（极值在边界取得）——这保证了 Dirichlet 问题解的唯一性。外问题（圆外）则保留 $r^{-n}$ 并要求 $r\to\infty$ 时有界。易错点：周期性条件给出的是整数 n（而非由边界零点决定的 $n\pi/L$）；$n=0$ 时径向解的特殊形式（常数 + $\ln r$）。",
    "extensions": [r"若 $f(\theta)=\cos\theta$，求具体解（$u=(r/a)\cos\theta$）。", r"写出 Poisson 积分公式并说明平均值定理。"],
  },
  {
    "subject": "数学物理方程", "question_type": "分析题",
    "question": r"什么是 Sturm-Liouville 本征值问题？简述本征值与本征函数的主要性质。",
    "answer": r"标准形式：$\frac{d}{dx}\left[p(x)\frac{dy}{dx}\right]+[\lambda\rho(x)-q(x)]y=0$ 配边值条件。主要性质：① 本征值非负且可排成递增无界序列 $\lambda_1<\lambda_2<\cdots\to\infty$；② 不同本征值对应的本征函数带权 $\rho(x)$ 正交；③ 本征函数系在相应函数空间中完备（可将任意函数展开为本征函数级数）。",
    "key_breakthrough": r"S-L 理论是分离变量法的「**理论保证**」：它告诉我们本征值存在、离散、可排序，本征函数正交且完备 —— 正因为这三条，我们才敢把解写成 $\sum c_n X_n(x)$ 并用正交性求系数。所有分离变量遇到的本征值问题（$\sin$、$\cos$、Bessel、Legendre）都是 S-L 问题的特例。",
    "knowledge_points": ["Sturm-Liouville", "本征值", "正交性", "完备性"],
    "knowledge_review": r"Sturm-Liouville 问题：$\frac{d}{dx}[p(x)y']+[\lambda\rho(x)-q(x)]y=0$（$a<x<b$）配分离型边界条件（如 $\alpha_1y(a)-\beta_1y'(a)=0$）。权函数 $\rho(x)>0$。三类边界组合分别对应前面提到的三类边界条件。核心定理：① 存在无穷多个实本征值 $\lambda_1<\lambda_2<\cdots\to\infty$（离散谱）；② 对应本征函数 $y_n$ 在 $[a,b]$ 上带权 $\rho$ 正交：$\int_a^b \rho y_my_ndx=0\ (m\neq n)$；③ 本征函数系完备：任意（满足条件的）函数 $f$ 可展开为广义傅里叶级数 $f=\sum c_ny_n$，$c_n=\frac{\int_a^b\rho f y_ndx}{\int_a^b\rho y_n^2dx}$（Parseval 等式成立）。典型特例：$y''+\lambda y=0$ 配不同边界条件 → $\sin$/$\cos$ 系（傅里叶级数）；Bessel 方程 → 贝塞尔函数系；Legendre 方程 → 勒让德多项式系。易错点：正交性是「带权正交」，权函数 $\rho(x)$ 不可遗漏（直角坐标问题中 $\rho=1$，但极坐标下 $\rho=r$）；本征值从哪个下标开始取决于是否有 $\lambda=0$。",
    "extensions": [r"验证 $\{\sin(n\pi x/L)\}$ 在 [0,L] 上的正交性。", r"写出 Bessel 函数作为 S-L 问题本征函数时的权函数。"],
  },
  {
    "subject": "数学物理方程", "question_type": "分析题",
    "question": r"简述贝塞尔函数与勒让德多项式分别出现在什么物理/几何背景下。",
    "answer": r"贝塞尔函数：在**柱坐标（或极坐标）**下分离变量求解 Laplace/Helmholtz/波动方程时出现（如圆柱体内的温度分布、圆膜的振动、圆柱形波导），对应径向方程 $r^2R''+rR'+(k^2r^2-n^2)R=0$。勒让德多项式：在**球坐标**下求解具有球对称性的问题（如球内外的引力势/静电势、$\nabla^2u=0$ 的球坐标分离变量），对应角向方程 $(1-x^2)y''-2xy'+l(l+1)y=0$。",
    "key_breakthrough": r"一句话记忆：**「柱/圆 → 贝塞尔；球 → 勒让德」**。它们都不是初等函数，而是「特殊函数」——因为柱坐标和球坐标下的分离变量方程不产生 $\sin/\cos$，而产生新的正交函数族。它们的作用与傅里叶级数完全一致（都是完备正交基），只是基函数换了。",
    "knowledge_points": ["贝塞尔函数", "勒让德多项式", "特殊函数", "柱坐标与球坐标"],
    "knowledge_review": r"特殊函数源于曲线坐标系下的分离变量。贝塞尔方程 $x^2y''+xy'+(x^2-n^2)y=0$，解为 n 阶贝塞尔函数 $J_n(x)$（第一类，在原点有界）与 $Y_n(x)$（第二类/诺依曼函数，在原点奇异）；物理问题中有界性要求通常舍去 $Y_n$。性质：$J_n$ 有无穷多个正零点（决定本征值）；带权 x 正交：$\int_0^a xJ_n(\alpha_ix)J_n(\alpha_jx)dx=0\ (i\neq j)$；递推关系与生成函数。勒让德方程 $(1-x^2)y''-2xy'+l(l+1)y=0$（$x=\cos\theta$），当 $l$ 为非负整数时有多项式解 $P_l(x)$（勒让德多项式，否则解在 $x=\pm1$ 发散）；正交性 $\int_{-1}^1P_lP_mdx=\frac{2}{2l+1}\delta_{lm}$；前几项 $P_0=1,\ P_1=x,\ P_2=\frac{3x^2-1}{2}$。二者都是 Sturm-Liouville 本征函数，可用于广义傅里叶展开。易错点：贝塞尔的本征值由边界条件（如 $J_n(ka)=0$ 的零点）确定，不是简单的整数；勒让德多项式的自变量是 $\cos\theta$ 而非角度本身。",
    "extensions": [r"写出圆膜振动（固定边界）的本征值与本征函数（含 $J_n$）。", r"写出 $P_0,P_1,P_2$ 并验证正交性。"],
  },
  {
    "subject": "数学物理方程", "question_type": "分析题",
    "question": r"什么是定解问题的适定性？以热传导方程的初值问题为例说明。",
    "answer": r"适定性（Hadamard）指定解问题同时满足：① 解存在；② 解唯一；③ 解连续依赖于定解数据（稳定性）。热传导方程的初值问题（$u_t=a^2u_{xx},\ u(x,0)=\varphi(x)$）是适定的：解由 Poisson 公式给出且存在唯一，且当初始数据有小扰动时解的变化也小（最大模估计保证）。反之，「反问题」（如由末时刻温度反推初始温度）通常不适定。",
    "key_breakthrough": r"适定性的三个要求中，**「稳定性」最容易被忽视却最关键**：它意味着「微小的测量误差不会导致结果天差地别」。数学物理方程若不适定，数值计算就毫无意义（舍入误差会被放大）。热传导的「反演」（倒推）就是典型不适定问题——因为热方程的衰减因子 $e^{-n^2t}$ 反推时要乘 $e^{+n^2t}$，高阶误差被指数放大。",
    "knowledge_points": ["适定性", "存在唯一性", "稳定性", "反问题"],
    "knowledge_review": r"Hadamard 适定性三要素：存在性、唯一性、连续依赖性（稳定性）。三类 PDE 的典型适定问题：① 双曲型（波动方程）：初值问题或混合问题适定；② 抛物型（热传导）：初值-边值问题正向（由初始推未来）适定，反向（初值反演）不适定（因高阶分量衰减快，反推时 $e^{n^2t}$ 放大误差）；③ 椭圆型（Laplace/Poisson）：边值问题（Dirichlet、Neumann、Robin）适定。证明工具：能量积分法（波动、热传导的唯一性与稳定性）、极值原理（椭圆与抛物）、Fourier 分析。不适定问题需正则化（如 Tikhonov 正则化）才能数值求解。物理意义：适定性对应「物理问题的因果关系合理、可预测」。易错点：唯一性不等于稳定性（存在唯一但不稳定的问题是可能的）；数值求解不适定问题需特殊处理。",
    "extensions": [r"解释为何「由末态温度反推初态」是不适定的（指数放大误差）。", r"用极值原理说明热传导方程解的唯一性。"],
  },
  {
    "subject": "数学物理方程", "question_type": "分析题",
    "question": r"简述用积分变换法（傅里叶变换或拉普拉斯变换）求解偏微分方程的基本思路与适用情形。",
    "answer": r"思路：对方程中某个自变量（通常是时间 t 或空间变量 x）作积分变换，把 PDE 化为关于该变量的常微分方程（或代数方程），求解后再作逆变换得到原解。傅里叶变换适合**无界空间域**（$-\infty<x<\infty$，如无限长弦、无限大平板的热传导）；拉普拉斯变换适合**时间变量**（$t\ge0$，初值问题，因它能自动把初始条件包含在变换中）。",
    "key_breakthrough": r"积分变换法的本质是「**降维**」：把对某个变量的导数变成乘法（$\frac{\partial}{\partial x}\to ik$、$\frac{\partial}{\partial t}\to s$），从而把偏微分方程降阶为常微分方程甚至代数方程。**选变换看变量范围**：x 在全直线用傅里叶、x 在半直线用拉普拉斯（或正弦/余弦变换）、t≥0 用拉普拉斯。",
    "knowledge_points": ["积分变换法", "傅里叶变换", "拉普拉斯变换", "降维"],
    "knowledge_review": r"积分变换法要点：① 选择对哪个变量变换（通常选取值域为 $(-\infty,\infty)$ 或 $[0,\infty)$ 的变量）；② 利用导数性质把 PDE 降为 ODE/代数方程（傅里叶：$\partial_x\to i\omega$、$\partial_x^2\to-\omega^2$；拉普拉斯：$\partial_t\to s-u(0)$）；③ 解 ODE 得到变换域的解（含初始条件或边界条件的变换）；④ 逆变换回原域（用变换表、留数定理或卷积定理）。典型：无限长弦振动用傅里叶变换（得 $\hat{u}_{tt}+a^2\omega^2\hat{u}=0$）；半无限长杆热传导可用拉普拉斯变换（对 t）或正弦变换（对 x）。有限区间问题则更适合分离变量法（本征函数展开）。混合方法：先对时间作拉普拉斯变换，再对空间用本征函数展开。易错点：变换后的初始条件处理（拉普拉斯变换的 $\mathcal{L}\{u_t\}=sU-u(x,0)$ 会引入初始条件项）；逆变换的计算（常用留数定理或部分分式）。",
    "extensions": [r"用傅里叶变换推导无限长弦振动的达朗贝尔解。", r"用拉普拉斯变换求解半无限长杆的热传导问题。"],
  },
]
