// 算法演示的多语言代码与「语义行号 → 真实行号」映射。
// 结构：ALGO_CODES[算法id] = {
//   codes:   { c: [行...], cpp: [行...], java: [行...], python: [行...] },
//   lineMap: { c: { 伪代码codeLine: 真实行号 }, cpp: {...}, java: {...}, python: {...} },
// }
// 说明：步骤生成器里的 codeLine 是「语义标签」（1=初始 / 比较 / 交换 / 完成 等，见各算法生成器），
// lineMap 把每个 codeLine 映射到对应语言代码里「做这件事」的那一行。树/图算法用「核心逻辑版」：
// 结构体/类定义用一行注释说明，只写算法核心，聚焦逻辑本身。

export const CODE_LANGS = [
  { key: 'c', label: 'C' },
  { key: 'cpp', label: 'C++' },
  { key: 'java', label: 'Java' },
  { key: 'python', label: 'Python' },
]

export const ALGO_CODES = {
  // ---------------- 冒泡排序 ----------------
  bubble: {
    codes: {
      c: [
        'void bubbleSort(int a[], int n) {',
        '    for (int i = 0; i < n - 1; i++) {',
        '        for (int j = 0; j < n - 1 - i; j++) {',
        '            if (a[j] > a[j + 1]) {',
        '                int t = a[j]; a[j] = a[j + 1]; a[j + 1] = t;',
        '            }',
        '        }',
        '    }',
        '}',
      ],
      cpp: [
        'void bubbleSort(int a[], int n) {',
        '    for (int i = 0; i < n - 1; i++) {',
        '        for (int j = 0; j < n - 1 - i; j++) {',
        '            if (a[j] > a[j + 1]) {',
        '                std::swap(a[j], a[j + 1]);',
        '            }',
        '        }',
        '    }',
        '}',
      ],
      java: [
        'void bubbleSort(int[] a) {',
        '    int n = a.length;',
        '    for (int i = 0; i < n - 1; i++) {',
        '        for (int j = 0; j < n - 1 - i; j++) {',
        '            if (a[j] > a[j + 1]) {',
        '                int t = a[j]; a[j] = a[j + 1]; a[j + 1] = t;',
        '            }',
        '        }',
        '    }',
        '}',
      ],
      python: [
        'def bubble_sort(a):',
        '    n = len(a)',
        '    for i in range(n - 1):',
        '        for j in range(n - 1 - i):',
        '            if a[j] > a[j + 1]:',
        '                a[j], a[j + 1] = a[j + 1], a[j]',
      ],
    },
    lineMap: {
      c: { 1: 1, 4: 4, 5: 5, 2: 7, 7: 8 },
      cpp: { 1: 1, 4: 4, 5: 5, 2: 7, 7: 8 },
      java: { 1: 3, 4: 5, 5: 6, 2: 8, 7: 9 },
      python: { 1: 1, 4: 5, 5: 6, 2: 4, 7: 6 },
    },
  },

  // ---------------- 选择排序 ----------------
  selection: {
    codes: {
      c: [
        'void selectionSort(int a[], int n) {',
        '    for (int i = 0; i < n - 1; i++) {',
        '        int min = i;',
        '        for (int j = i + 1; j < n; j++) {',
        '            if (a[j] < a[min]) {',
        '                min = j;',
        '            }',
        '        }',
        '        int t = a[i]; a[i] = a[min]; a[min] = t;',
        '    }',
        '}',
      ],
      cpp: [
        'void selectionSort(int a[], int n) {',
        '    for (int i = 0; i < n - 1; i++) {',
        '        int min = i;',
        '        for (int j = i + 1; j < n; j++) {',
        '            if (a[j] < a[min]) {',
        '                min = j;',
        '            }',
        '        }',
        '        std::swap(a[i], a[min]);',
        '    }',
        '}',
      ],
      java: [
        'void selectionSort(int[] a) {',
        '    int n = a.length;',
        '    for (int i = 0; i < n - 1; i++) {',
        '        int min = i;',
        '        for (int j = i + 1; j < n; j++) {',
        '            if (a[j] < a[min]) {',
        '                min = j;',
        '            }',
        '        }',
        '        int t = a[i]; a[i] = a[min]; a[min] = t;',
        '    }',
        '}',
      ],
      python: [
        'def selection_sort(a):',
        '    n = len(a)',
        '    for i in range(n - 1):',
        '        m = i',
        '        for j in range(i + 1, n):',
        '            if a[j] < a[m]:',
        '                m = j',
        '        a[i], a[m] = a[m], a[i]',
      ],
    },
    lineMap: {
      c: { 1: 1, 3: 3, 4: 5, 5: 6, 6: 9, 2: 8, 8: 10 },
      cpp: { 1: 1, 3: 3, 4: 5, 5: 6, 6: 9, 2: 8, 8: 10 },
      java: { 1: 3, 3: 4, 4: 6, 5: 7, 6: 10, 2: 9, 8: 11 },
      python: { 1: 1, 3: 4, 4: 6, 5: 7, 6: 8, 2: 5, 8: 8 },
    },
  },

  // ---------------- 插入排序 ----------------
  insertion: {
    codes: {
      c: [
        'void insertionSort(int a[], int n) {',
        '    for (int i = 1; i < n; i++) {',
        '        int key = a[i];',
        '        int j = i - 1;',
        '        while (j >= 0 && a[j] > key) {',
        '            a[j + 1] = a[j];',
        '            j--;',
        '        }',
        '        a[j + 1] = key;',
        '    }',
        '}',
      ],
      cpp: [
        'void insertionSort(int a[], int n) {',
        '    for (int i = 1; i < n; i++) {',
        '        int key = a[i];',
        '        int j = i - 1;',
        '        while (j >= 0 && a[j] > key) {',
        '            a[j + 1] = a[j];',
        '            j--;',
        '        }',
        '        a[j + 1] = key;',
        '    }',
        '}',
      ],
      java: [
        'void insertionSort(int[] a) {',
        '    int n = a.length;',
        '    for (int i = 1; i < n; i++) {',
        '        int key = a[i];',
        '        int j = i - 1;',
        '        while (j >= 0 && a[j] > key) {',
        '            a[j + 1] = a[j];',
        '            j--;',
        '        }',
        '        a[j + 1] = key;',
        '    }',
        '}',
      ],
      python: [
        'def insertion_sort(a):',
        '    for i in range(1, len(a)):',
        '        key = a[i]',
        '        j = i - 1',
        '        while j >= 0 and a[j] > key:',
        '            a[j + 1] = a[j]',
        '            j -= 1',
        '        a[j + 1] = key',
      ],
    },
    lineMap: {
      c: { 1: 1, 3: 3, 5: 6, 6: 9, 7: 10 },
      cpp: { 1: 1, 3: 3, 5: 6, 6: 9, 7: 10 },
      java: { 1: 3, 3: 4, 5: 7, 6: 10, 7: 11 },
      python: { 1: 1, 3: 3, 5: 6, 6: 8, 7: 8 },
    },
  },

  // ---------------- 快速排序 ----------------
  quick: {
    codes: {
      c: [
        'void quickSort(int a[], int low, int high) {',
        '    if (low >= high) return;',
        '    int pivot = a[low];',
        '    int i = low, j = high;',
        '    while (i < j) {',
        '        while (i < j && a[j] >= pivot) j--;',
        '        a[i] = a[j];',
        '        while (i < j && a[i] <= pivot) i++;',
        '        a[j] = a[i];',
        '    }',
        '    a[i] = pivot;',
        '    quickSort(a, low, i - 1);',
        '    quickSort(a, i + 1, high);',
        '}',
      ],
      cpp: [
        'void quickSort(int a[], int low, int high) {',
        '    if (low >= high) return;',
        '    int pivot = a[low];',
        '    int i = low, j = high;',
        '    while (i < j) {',
        '        while (i < j && a[j] >= pivot) j--;',
        '        a[i] = a[j];',
        '        while (i < j && a[i] <= pivot) i++;',
        '        a[j] = a[i];',
        '    }',
        '    a[i] = pivot;',
        '    quickSort(a, low, i - 1);',
        '    quickSort(a, i + 1, high);',
        '}',
      ],
      java: [
        'void quickSort(int[] a, int low, int high) {',
        '    if (low >= high) return;',
        '    int pivot = a[low];',
        '    int i = low, j = high;',
        '    while (i < j) {',
        '        while (i < j && a[j] >= pivot) j--;',
        '        a[i] = a[j];',
        '        while (i < j && a[i] <= pivot) i++;',
        '        a[j] = a[i];',
        '    }',
        '    a[i] = pivot;',
        '    quickSort(a, low, i - 1);',
        '    quickSort(a, i + 1, high);',
        '}',
      ],
      python: [
        'def quick_sort(a, low, high):',
        '    if low >= high:',
        '        return',
        '    pivot = a[low]',
        '    i, j = low, high',
        '    while i < j:',
        '        while i < j and a[j] >= pivot:',
        '            j -= 1',
        '        a[i] = a[j]',
        '        while i < j and a[i] <= pivot:',
        '            i += 1',
        '        a[j] = a[i]',
        '    a[i] = pivot',
        '    quick_sort(a, low, i - 1)',
        '    quick_sort(a, i + 1, high)',
      ],
    },
    lineMap: {
      c: { 1: 1, 3: 3, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 12: 13 },
      cpp: { 1: 1, 3: 3, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 12: 13 },
      java: { 1: 1, 3: 3, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 12: 13 },
      python: { 1: 1, 3: 4, 5: 7, 6: 9, 7: 10, 8: 12, 9: 13, 10: 14, 12: 15 },
    },
  },

  // ---------------- 归并排序 ----------------
  merge: {
    codes: {
      c: [
        'void merge(int a[], int l, int mid, int r) {',
        '    int i = l, j = mid + 1;',
        '    while (i <= mid && j <= r) {',
        '        if (a[i] <= a[j]) i++;',
        '        else j++;',
        '    }',
        '    // 合并结果写回 a[l..r]',
        '}',
        'void mergeSort(int a[], int l, int r) {',
        '    if (l >= r) return;',
        '    int mid = (l + r) / 2;',
        '    mergeSort(a, l, mid);',
        '    mergeSort(a, mid + 1, r);',
        '    merge(a, l, mid, r);',
        '}',
      ],
      cpp: [
        'void merge(int a[], int l, int mid, int r) {',
        '    int i = l, j = mid + 1;',
        '    while (i <= mid && j <= r) {',
        '        if (a[i] <= a[j]) i++;',
        '        else j++;',
        '    }',
        '    // 合并结果写回 a[l..r]',
        '}',
        'void mergeSort(int a[], int l, int r) {',
        '    if (l >= r) return;',
        '    int mid = (l + r) / 2;',
        '    mergeSort(a, l, mid);',
        '    mergeSort(a, mid + 1, r);',
        '    merge(a, l, mid, r);',
        '}',
      ],
      java: [
        'void merge(int[] a, int l, int mid, int r) {',
        '    int i = l, j = mid + 1;',
        '    while (i <= mid && j <= r) {',
        '        if (a[i] <= a[j]) i++;',
        '        else j++;',
        '    }',
        '    // 合并结果写回 a[l..r]',
        '}',
        'void mergeSort(int[] a, int l, int r) {',
        '    if (l >= r) return;',
        '    int mid = (l + r) / 2;',
        '    mergeSort(a, l, mid);',
        '    mergeSort(a, mid + 1, r);',
        '    merge(a, l, mid, r);',
        '}',
      ],
      python: [
        'def merge(a, l, mid, r):',
        '    i, j = l, mid + 1',
        '    while i <= mid and j <= r:',
        '        if a[i] <= a[j]:',
        '            i += 1',
        '        else:',
        '            j += 1',
        '    # 合并结果写回 a[l..r]',
        'def merge_sort(a, l, r):',
        '    if l >= r:',
        '        return',
        '    mid = (l + r) // 2',
        '    merge_sort(a, l, mid)',
        '    merge_sort(a, mid + 1, r)',
        '    merge(a, l, mid, r)',
      ],
    },
    lineMap: {
      c: { 1: 9, 3: 11, 5: 4, 7: 7, 8: 8, 10: 13 },
      cpp: { 1: 9, 3: 11, 5: 4, 7: 7, 8: 8, 10: 13 },
      java: { 1: 9, 3: 11, 5: 4, 7: 7, 8: 8, 10: 13 },
      python: { 1: 9, 3: 12, 5: 4, 7: 8, 8: 8, 10: 14 },
    },
  },

  // ---------------- 堆排序 ----------------
  heap: {
    codes: {
      c: [
        'void siftDown(int a[], int n, int root) {',
        '    while (2 * root + 1 < n) {',
        '        int child = 2 * root + 1;',
        '        if (child + 1 < n && a[child] < a[child + 1]) child++;',
        '        if (a[root] < a[child]) {',
        '            int t = a[root]; a[root] = a[child]; a[child] = t;',
        '            root = child;',
        '        } else break;',
        '    }',
        '}',
        'void heapSort(int a[], int n) {',
        '    for (int i = n / 2 - 1; i >= 0; i--) siftDown(a, n, i);',
        '    for (int end = n - 1; end > 0; end--) {',
        '        int t = a[0]; a[0] = a[end]; a[end] = t;',
        '        siftDown(a, end, 0);',
        '    }',
        '}',
      ],
      cpp: [
        'void siftDown(int a[], int n, int root) {',
        '    while (2 * root + 1 < n) {',
        '        int child = 2 * root + 1;',
        '        if (child + 1 < n && a[child] < a[child + 1]) child++;',
        '        if (a[root] < a[child]) {',
        '            std::swap(a[root], a[child]);',
        '            root = child;',
        '        } else break;',
        '    }',
        '}',
        'void heapSort(int a[], int n) {',
        '    for (int i = n / 2 - 1; i >= 0; i--) siftDown(a, n, i);',
        '    for (int end = n - 1; end > 0; end--) {',
        '        std::swap(a[0], a[end]);',
        '        siftDown(a, end, 0);',
        '    }',
        '}',
      ],
      java: [
        'void siftDown(int[] a, int n, int root) {',
        '    while (2 * root + 1 < n) {',
        '        int child = 2 * root + 1;',
        '        if (child + 1 < n && a[child] < a[child + 1]) child++;',
        '        if (a[root] < a[child]) {',
        '            int t = a[root]; a[root] = a[child]; a[child] = t;',
        '            root = child;',
        '        } else break;',
        '    }',
        '}',
        'void heapSort(int[] a) {',
        '    int n = a.length;',
        '    for (int i = n / 2 - 1; i >= 0; i--) siftDown(a, n, i);',
        '    for (int end = n - 1; end > 0; end--) {',
        '        int t = a[0]; a[0] = a[end]; a[end] = t;',
        '        siftDown(a, end, 0);',
        '    }',
        '}',
      ],
      python: [
        'def sift_down(a, n, root):',
        '    while 2 * root + 1 < n:',
        '        child = 2 * root + 1',
        '        if child + 1 < n and a[child] < a[child + 1]:',
        '            child += 1',
        '        if a[root] < a[child]:',
        '            a[root], a[child] = a[child], a[root]',
        '            root = child',
        '        else:',
        '            break',
        'def heap_sort(a):',
        '    n = len(a)',
        '    for i in range(n // 2 - 1, -1, -1):',
        '        sift_down(a, n, i)',
        '    for end in range(n - 1, 0, -1):',
        '        a[0], a[end] = a[end], a[0]',
        '        sift_down(a, end, 0)',
      ],
    },
    lineMap: {
      c: { 1: 11, 3: 12, 4: 4, 5: 5, 6: 6, 8: 14, 9: 15, 11: 16 },
      cpp: { 1: 11, 3: 12, 4: 4, 5: 5, 6: 6, 8: 14, 9: 15, 11: 16 },
      java: { 1: 11, 3: 13, 4: 4, 5: 5, 6: 6, 8: 15, 9: 16, 11: 17 },
      python: { 1: 11, 3: 13, 4: 4, 5: 6, 6: 7, 8: 16, 9: 17, 11: 17 },
    },
  },

  // ---------------- 二分查找 ----------------
  binary: {
    codes: {
      c: [
        'int binarySearch(int a[], int n, int target) {',
        '    int l = 0, r = n - 1;',
        '    while (l <= r) {',
        '        int mid = (l + r) / 2;',
        '        if (a[mid] == target) return mid;',
        '        if (a[mid] < target) l = mid + 1;',
        '        else r = mid - 1;',
        '    }',
        '    return -1;',
        '}',
      ],
      cpp: [
        'int binarySearch(int a[], int n, int target) {',
        '    int l = 0, r = n - 1;',
        '    while (l <= r) {',
        '        int mid = (l + r) / 2;',
        '        if (a[mid] == target) return mid;',
        '        if (a[mid] < target) l = mid + 1;',
        '        else r = mid - 1;',
        '    }',
        '    return -1;',
        '}',
      ],
      java: [
        'int binarySearch(int[] a, int target) {',
        '    int n = a.length;',
        '    int l = 0, r = n - 1;',
        '    while (l <= r) {',
        '        int mid = (l + r) / 2;',
        '        if (a[mid] == target) return mid;',
        '        if (a[mid] < target) l = mid + 1;',
        '        else r = mid - 1;',
        '    }',
        '    return -1;',
        '}',
      ],
      python: [
        'def binary_search(a, target):',
        '    l, r = 0, len(a) - 1',
        '    while l <= r:',
        '        mid = (l + r) // 2',
        '        if a[mid] == target:',
        '            return mid',
        '        if a[mid] < target:',
        '            l = mid + 1',
        '        else:',
        '            r = mid - 1',
        '    return -1',
      ],
    },
    lineMap: {
      c: { 1: 1, 3: 4, 4: 5, 5: 5, 7: 6, 6: 7, 9: 9 },
      cpp: { 1: 1, 3: 4, 4: 5, 5: 5, 7: 6, 6: 7, 9: 9 },
      java: { 1: 1, 3: 5, 4: 6, 5: 6, 7: 7, 6: 8, 9: 10 },
      python: { 1: 1, 3: 4, 4: 5, 5: 5, 7: 7, 6: 9, 9: 11 },
    },
  },

  // ---------------- 前序遍历 ----------------
  preorder: {
    codes: {
      c: [
        '// 节点结构 Node { left, right, val } 已定义',
        'void preorder(Node* node) {',
        '    if (node == NULL) return;',
        '    visit(node);              // 访问当前节点',
        '    preorder(node->left);',
        '    preorder(node->right);',
        '}',
      ],
      cpp: [
        '// 节点结构 Node { left, right, val } 已定义',
        'void preorder(Node* node) {',
        '    if (node == nullptr) return;',
        '    visit(node);              // 访问当前节点',
        '    preorder(node->left);',
        '    preorder(node->right);',
        '}',
      ],
      java: [
        '// 节点类 Node { left, right, val } 已定义',
        'void preorder(Node node) {',
        '    if (node == null) return;',
        '    visit(node);              // 访问当前节点',
        '    preorder(node.left);',
        '    preorder(node.right);',
        '}',
      ],
      python: [
        '# 节点类 Node（含 left/right/val）已定义',
        'def preorder(node):',
        '    if node is None:',
        '        return',
        '    visit(node)      # 访问当前节点',
        '    preorder(node.left)',
        '    preorder(node.right)',
      ],
    },
    lineMap: {
      c: { 1: 2, 3: 4, 6: 6 },
      cpp: { 1: 2, 3: 4, 6: 6 },
      java: { 1: 2, 3: 4, 6: 6 },
      python: { 1: 2, 3: 5, 6: 7 },
    },
  },

  // ---------------- 中序遍历 ----------------
  inorder: {
    codes: {
      c: [
        '// 节点结构 Node { left, right, val } 已定义',
        'void inorder(Node* node) {',
        '    if (node == NULL) return;',
        '    inorder(node->left);',
        '    visit(node);              // 访问当前节点',
        '    inorder(node->right);',
        '}',
      ],
      cpp: [
        '// 节点结构 Node { left, right, val } 已定义',
        'void inorder(Node* node) {',
        '    if (node == nullptr) return;',
        '    inorder(node->left);',
        '    visit(node);              // 访问当前节点',
        '    inorder(node->right);',
        '}',
      ],
      java: [
        '// 节点类 Node { left, right, val } 已定义',
        'void inorder(Node node) {',
        '    if (node == null) return;',
        '    inorder(node.left);',
        '    visit(node);              // 访问当前节点',
        '    inorder(node.right);',
        '}',
      ],
      python: [
        '# 节点类 Node（含 left/right/val）已定义',
        'def inorder(node):',
        '    if node is None:',
        '        return',
        '    inorder(node.left)',
        '    visit(node)      # 访问当前节点',
        '    inorder(node.right)',
      ],
    },
    lineMap: {
      c: { 1: 2, 4: 5, 6: 6 },
      cpp: { 1: 2, 4: 5, 6: 6 },
      java: { 1: 2, 4: 5, 6: 6 },
      python: { 1: 2, 4: 6, 6: 7 },
    },
  },

  // ---------------- 后序遍历 ----------------
  postorder: {
    codes: {
      c: [
        '// 节点结构 Node { left, right, val } 已定义',
        'void postorder(Node* node) {',
        '    if (node == NULL) return;',
        '    postorder(node->left);',
        '    postorder(node->right);',
        '    visit(node);              // 访问当前节点',
        '}',
      ],
      cpp: [
        '// 节点结构 Node { left, right, val } 已定义',
        'void postorder(Node* node) {',
        '    if (node == nullptr) return;',
        '    postorder(node->left);',
        '    postorder(node->right);',
        '    visit(node);              // 访问当前节点',
        '}',
      ],
      java: [
        '// 节点类 Node { left, right, val } 已定义',
        'void postorder(Node node) {',
        '    if (node == null) return;',
        '    postorder(node.left);',
        '    postorder(node.right);',
        '    visit(node);              // 访问当前节点',
        '}',
      ],
      python: [
        '# 节点类 Node（含 left/right/val）已定义',
        'def postorder(node):',
        '    if node is None:',
        '        return',
        '    postorder(node.left)',
        '    postorder(node.right)',
        '    visit(node)      # 访问当前节点',
      ],
    },
    lineMap: {
      c: { 1: 2, 5: 6, 6: 6 },
      cpp: { 1: 2, 5: 6, 6: 6 },
      java: { 1: 2, 5: 6, 6: 6 },
      python: { 1: 2, 5: 7, 6: 7 },
    },
  },

  // ---------------- 层序遍历 ----------------
  levelorder: {
    codes: {
      c: [
        '// 节点结构 Node { left, right, val } 已定义；队列 Queue 已定义',
        'void levelorder(Node* root) {',
        '    enqueue(root);',
        '    while (!queueEmpty()) {',
        '        Node* node = dequeue();',
        '        visit(node);              // 访问当前节点',
        '        if (node->left) enqueue(node->left);',
        '        if (node->right) enqueue(node->right);',
        '    }',
        '}',
      ],
      cpp: [
        '// 节点结构 Node { left, right, val } 已定义；队列 std::queue 已定义',
        'void levelorder(Node* root) {',
        '    queue<Node*> q; q.push(root);',
        '    while (!q.empty()) {',
        '        Node* node = q.front(); q.pop();',
        '        visit(node);              // 访问当前节点',
        '        if (node->left) q.push(node->left);',
        '        if (node->right) q.push(node->right);',
        '    }',
        '}',
      ],
      java: [
        '// 节点类 Node { left, right, val } 已定义；队列 Queue 已定义',
        'void levelorder(Node root) {',
        '    Queue<Node> q = new LinkedList<>(); q.add(root);',
        '    while (!q.isEmpty()) {',
        '        Node node = q.poll();',
        '        visit(node);              // 访问当前节点',
        '        if (node.left != null) q.add(node.left);',
        '        if (node.right != null) q.add(node.right);',
        '    }',
        '}',
      ],
      python: [
        '# 节点类 Node（含 left/right/val）已定义',
        'def levelorder(root):',
        '    queue = [root]',
        '    while queue:',
        '        node = queue.pop(0)',
        '        visit(node)      # 访问当前节点',
        '        if node.left:',
        '            queue.append(node.left)',
        '        if node.right:',
        '            queue.append(node.right)',
      ],
    },
    lineMap: {
      c: { 2: 3, 4: 6, 5: 7, 6: 8, 7: 9 },
      cpp: { 2: 3, 4: 6, 5: 7, 6: 8, 7: 9 },
      java: { 2: 3, 4: 6, 5: 7, 6: 8, 7: 9 },
      python: { 2: 3, 4: 6, 5: 7, 6: 9, 7: 10 },
    },
  },

  // ---------------- BST 查找 ----------------
  bst_search: {
    codes: {
      c: [
        '// 节点结构 Node { left, right, val } 已定义',
        'Node* search(Node* node, int target) {',
        '    if (node == NULL) return NULL;',
        '    if (node->val == target) return node;   // 找到',
        '    if (target < node->val) return search(node->left, target);',
        '    return search(node->right, target);',
        '}',
      ],
      cpp: [
        '// 节点结构 Node { left, right, val } 已定义',
        'Node* search(Node* node, int target) {',
        '    if (node == nullptr) return nullptr;',
        '    if (node->val == target) return node;   // 找到',
        '    if (target < node->val) return search(node->left, target);',
        '    return search(node->right, target);',
        '}',
      ],
      java: [
        '// 节点类 Node { left, right, val } 已定义',
        'Node search(Node node, int target) {',
        '    if (node == null) return null;',
        '    if (node.val == target) return node;   // 找到',
        '    if (target < node.val) return search(node.left, target);',
        '    return search(node.right, target);',
        '}',
      ],
      python: [
        '# 节点类 Node（含 left/right/val）已定义',
        'def search(node, target):',
        '    if node is None:',
        '        return None',
        '    if node.val == target:',
        '        return node',
        '    if target < node.val:',
        '        return search(node.left, target)',
        '    return search(node.right, target)',
      ],
    },
    lineMap: {
      c: { 1: 2, 2: 4, 3: 4, 4: 5, 5: 6, 7: 3 },
      cpp: { 1: 2, 2: 4, 3: 4, 4: 5, 5: 6, 7: 3 },
      java: { 1: 2, 2: 4, 3: 4, 4: 5, 5: 6, 7: 3 },
      python: { 1: 2, 2: 5, 3: 5, 4: 7, 5: 9, 7: 3 },
    },
  },

  // ---------------- BFS ----------------
  bfs: {
    codes: {
      c: [
        '// 图以邻接表表示；队列 Queue 已定义；visited[] 标记',
        'void bfs(int start) {',
        '    enqueue(start); visited[start] = 1;',
        '    while (!queueEmpty()) {',
        '        int u = dequeue();',
        '        visit(u);              // 访问当前节点',
        '        for (每个邻居 v of u) {',
        '            if (!visited[v]) {',
        '                visited[v] = 1; enqueue(v);',
        '            }',
        '        }',
        '    }',
        '}',
      ],
      cpp: [
        '// 图以邻接表表示；队列 std::queue 已定义；visited[] 标记',
        'void bfs(int start) {',
        '    queue<int> q; q.push(start); visited[start] = 1;',
        '    while (!q.empty()) {',
        '        int u = q.front(); q.pop();',
        '        visit(u);              // 访问当前节点',
        '        for (int v : adj[u]) {',
        '            if (!visited[v]) {',
        '                visited[v] = 1; q.push(v);',
        '            }',
        '        }',
        '    }',
        '}',
      ],
      java: [
        '// 图以邻接表表示；队列 Queue 已定义；visited[] 标记',
        'void bfs(int start) {',
        '    Queue<Integer> q = new LinkedList<>(); q.add(start); visited[start] = 1;',
        '    while (!q.isEmpty()) {',
        '        int u = q.poll();',
        '        visit(u);              // 访问当前节点',
        '        for (int v : adj[u]) {',
        '            if (visited[v] == 0) {',
        '                visited[v] = 1; q.add(v);',
        '            }',
        '        }',
        '    }',
        '}',
      ],
      python: [
        '# 图以邻接表 adj 表示；visited 为集合',
        'def bfs(start):',
        '    queue = [start]',
        '    visited.add(start)',
        '    while queue:',
        '        u = queue.pop(0)',
        '        visit(u)       # 访问当前节点',
        '        for v in adj[u]:',
        '            if v not in visited:',
        '                visited.add(v)',
        '                queue.append(v)',
      ],
    },
    lineMap: {
      c: { 2: 3, 4: 6, 6: 9, 8: 12 },
      cpp: { 2: 3, 4: 6, 6: 9, 8: 12 },
      java: { 2: 3, 4: 6, 6: 9, 8: 12 },
      python: { 2: 3, 4: 7, 6: 9, 8: 11 },
    },
  },

  // ---------------- DFS ----------------
  dfs: {
    codes: {
      c: [
        '// 图以邻接表表示；visited[] 标记',
        'void dfs(int u) {',
        '    visited[u] = 1;',
        '    visit(u);              // 访问当前节点',
        '    for (每个邻居 v of u) {',
        '        if (!visited[v]) {',
        '            dfs(v);        // 递归深入',
        '        }',
        '    }',
        '    // u 的邻接访问完，回溯',
        '}',
      ],
      cpp: [
        '// 图以邻接表表示；visited[] 标记',
        'void dfs(int u) {',
        '    visited[u] = 1;',
        '    visit(u);              // 访问当前节点',
        '    for (int v : adj[u]) {',
        '        if (!visited[v]) {',
        '            dfs(v);        // 递归深入',
        '        }',
        '    }',
        '    // u 的邻接访问完，回溯',
        '}',
      ],
      java: [
        '// 图以邻接表表示；visited[] 标记',
        'void dfs(int u) {',
        '    visited[u] = 1;',
        '    visit(u);              // 访问当前节点',
        '    for (int v : adj[u]) {',
        '        if (visited[v] == 0) {',
        '            dfs(v);        // 递归深入',
        '        }',
        '    }',
        '    // u 的邻接访问完，回溯',
        '}',
      ],
      python: [
        '# 图以邻接表 adj 表示；visited 为集合',
        'def dfs(u):',
        '    visited.add(u)',
        '    visit(u)       # 访问当前节点',
        '    for v in adj[u]:',
        '        if v not in visited:',
        '            dfs(v)      # 递归深入',
        '    # u 的邻接访问完，回溯',
      ],
    },
    lineMap: {
      c: { 1: 2, 3: 4, 4: 7, 5: 10, 6: 9 },
      cpp: { 1: 2, 3: 4, 4: 7, 5: 10, 6: 9 },
      java: { 1: 2, 3: 4, 4: 7, 5: 10, 6: 9 },
      python: { 1: 2, 3: 4, 4: 7, 5: 8, 6: 8 },
    },
  },

  // ---------------- Dijkstra ----------------
  dijkstra: {
    codes: {
      c: [
        '// 图以邻接表表示（边带权 w）；dist[] 初始 INF，done[] 标记已确定',
        'void dijkstra(int start) {',
        '    dist[start] = 0;',
        '    for (int k = 0; k < n; k++) {',
        '        int u = -1;',
        '        for (int i = 0; i < n; i++)',
        '            if (!done[i] && (u == -1 || dist[i] < dist[u])) u = i;',
        '        done[u] = 1;',
        '        for (每个邻居 (v, w) of u) {',
        '            if (dist[u] + w < dist[v]) {',
        '                dist[v] = dist[u] + w;   // 松弛',
        '            }',
        '        }',
        '    }',
        '}',
      ],
      cpp: [
        '// 图以邻接表表示（边带权 w）；dist[] 初始 INF，done[] 标记已确定',
        'void dijkstra(int start) {',
        '    dist[start] = 0;',
        '    for (int k = 0; k < n; k++) {',
        '        int u = -1;',
        '        for (int i = 0; i < n; i++)',
        '            if (!done[i] && (u == -1 || dist[i] < dist[u])) u = i;',
        '        done[u] = 1;',
        '        for (每个邻居 (v, w) of u) {',
        '            if (dist[u] + w < dist[v]) {',
        '                dist[v] = dist[u] + w;   // 松弛',
        '            }',
        '        }',
        '    }',
        '}',
      ],
      java: [
        '// 图以邻接表表示（边带权 w）；dist[] 初始为无穷大，done[] 标记已确定',
        'void dijkstra(int start) {',
        '    dist[start] = 0;',
        '    for (int k = 0; k < n; k++) {',
        '        int u = -1;',
        '        for (int i = 0; i < n; i++)',
        '            if (done[i] == 0 && (u == -1 || dist[i] < dist[u])) u = i;',
        '        done[u] = 1;',
        '        for (每个邻居 (v, w) of u) {',
        '            if (dist[u] + w < dist[v]) {',
        '                dist[v] = dist[u] + w;   // 松弛',
        '            }',
        '        }',
        '    }',
        '}',
      ],
      python: [
        '# 图以邻接表 adj 表示（边带权 w）；dist 初始为无穷大，done 标记已确定',
        'def dijkstra(start):',
        '    dist[start] = 0',
        '    for _ in range(n):',
        '        u = -1',
        '        for i in range(n):',
        '            if not done[i] and (u == -1 or dist[i] < dist[u]):',
        '                u = i',
        '        done[u] = True',
        '        for v, w in adj[u]:',
        '            if dist[u] + w < dist[v]:',
        '                dist[v] = dist[u] + w   # 松弛',
      ],
    },
    lineMap: {
      c: { 1: 3, 3: 8, 5: 11, 7: 14 },
      cpp: { 1: 3, 3: 8, 5: 11, 7: 14 },
      java: { 1: 3, 3: 8, 5: 11, 7: 14 },
      python: { 1: 3, 3: 9, 5: 12, 7: 12 },
    },
  },
}
